// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: CWatch

#ifndef _CWATCH_UI_H
#define _CWATCH_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl/lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"


///////////////////// SCREENS ////////////////////

#include "screens/ui_Screen1.h"
#include "screens/ui_Screen2.h"
#include "screens/ui_Screen3.h"
#include "screens/ui_Screen5.h"
#include "screens/ui_Screen6.h"
#include "screens/ui_Screen7.h"
#include "screens/ui_weather.h"
#include "screens/ui_weather2.h"

///////////////////// VARIABLES ////////////////////

extern lv_anim_t * blood1_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * blood2_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * heart_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * top_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * button_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * opa_Animation(lv_obj_t * TargetObject, int delay);

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_battery_png);    // assets/battery.png
LV_IMG_DECLARE(ui_img_1883903296);    // assets/heart (2).png
LV_IMG_DECLARE(ui_img_o2_png);    // assets/O2.png
LV_IMG_DECLARE(ui_img_foot_png);    // assets/foot.png
LV_IMG_DECLARE(ui_img_hot_png);    // assets/hot.png
LV_IMG_DECLARE(ui_img_wave2_png);    // assets/wave2.png
LV_IMG_DECLARE(ui_img_wave1_png);    // assets/wave1.png
LV_IMG_DECLARE(ui_img_heart_png);    // assets/heart.png
LV_IMG_DECLARE(ui_img_pngsucai_3128177_ef13f6_png);    // assets/pngsucai_3128177_ef13f6.png
LV_IMG_DECLARE(ui_img_arrow_png);    // assets/arrow.png
LV_IMG_DECLARE(
    ui_img_gemini_generated_image_fdcqbnfdcqbnfdcq_png);    // assets/Gemini_Generated_Image_fdcqbnfdcqbnfdcq.png
LV_IMG_DECLARE(ui_img_altitude_png);    // assets/altitude.png
LV_IMG_DECLARE(ui_img_hum_png);    // assets/hum.png
LV_IMG_DECLARE(ui_img_press_png);    // assets/press.png
LV_IMG_DECLARE(ui_img_temp_png);    // assets/temp.png
LV_IMG_DECLARE(ui_img_wsun_png);    // assets/wsun.png
LV_IMG_DECLARE(ui_img_weather_sun_cloud_png);    // assets/weather_sun_cloud.png
LV_IMG_DECLARE(ui_img_weather_cloud_png);    
LV_IMG_DECLARE(ui_img_weather_sun_png);    
LV_IMG_DECLARE(ui_img_wrain_png);
LV_IMG_DECLARE(ui_img_wcloud_png);
LV_IMG_DECLARE(ui_img_compass_png);
LV_IMG_DECLARE(ui_img_light_png);
LV_IMG_DECLARE(ui_img_heart1_png);
LV_IMG_DECLARE(ui_img_setting_png);
LV_IMG_DECLARE(ui_img_env_png);

// FONTS
LV_FONT_DECLARE(ui_font_chinese);
LV_FONT_DECLARE(ui_font_chinese2);
LV_FONT_DECLARE(ui_font_large);
LV_FONT_DECLARE(ui_font_large_promax);

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
