// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: CWatch

#include "../ui.h"

#define ABOUT_APP_NAME "CWatch"
#define ABOUT_AUTHOR   "作者: czh-hzc"
#define ABOUT_VERSION  "版本: V1.0.0"

lv_obj_t * ui_about = NULL;

// event funtions
void ui_event_about(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE && lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_Screen7, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 150, 0, &ui_Screen7_screen_init);
    }
}

static void ui_about_create_label(lv_obj_t * parent, const char * text, lv_coord_t y, const lv_font_t * font)
{
    lv_obj_t * label = lv_label_create(parent);
    lv_obj_set_width(label, lv_pct(100));
    lv_obj_set_height(label, LV_SIZE_CONTENT);
    lv_obj_set_align(label, LV_ALIGN_CENTER);
    lv_obj_set_y(label, y);
    lv_label_set_text(label, text);
    lv_obj_set_style_text_align(label, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(label, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(label, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(label, font, LV_PART_MAIN | LV_STATE_DEFAULT);
}

// build funtions
void ui_about_screen_init(void)
{
    ui_about = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_about, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_about, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_about, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_about, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_about_create_label(ui_about, ABOUT_APP_NAME, -80, &ui_font_large);
    ui_about_create_label(ui_about, ABOUT_AUTHOR, 0, &ui_font_chinese2);
    ui_about_create_label(ui_about, ABOUT_VERSION, 48, &ui_font_chinese2);

    lv_obj_add_event_cb(ui_about, ui_event_about, LV_EVENT_ALL, NULL);
}

void ui_about_screen_destroy(void)
{
    if(ui_about) lv_obj_del(ui_about);

    // NULL screen variables
    ui_about = NULL;
}
