// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: CWatch

#include "../ui.h"

lv_obj_t * ui_Screen5 = NULL;
lv_obj_t * ui_Image1 = NULL;
lv_obj_t * ui_alti_arc2 = NULL;
lv_obj_t * ui_press_arc3 = NULL;
lv_obj_t * ui_temp_arc4 = NULL;
lv_obj_t * ui_hum_arc5 = NULL;
lv_obj_t * ui_alti = NULL;
lv_obj_t * ui_hum = NULL;
lv_obj_t * ui_press = NULL;
lv_obj_t * ui_temp = NULL;
lv_obj_t * ui_press_test = NULL;
lv_obj_t * ui_presstext2 = NULL;
lv_obj_t * ui_hum_test = NULL;
lv_obj_t * ui_humtext1 = NULL;
lv_obj_t * ui_temp_test = NULL;
lv_obj_t * ui_temptext = NULL;
lv_obj_t * ui_alti_test = NULL;
lv_obj_t * ui_altitext = NULL;
// event funtions
void ui_event_Screen5(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_FADE_ON, 100, 0, &ui_Screen1_screen_init);
    }
}

// build funtions

void ui_Screen5_screen_init(void)
{
    ui_Screen5 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen5, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image1 = lv_img_create(ui_Screen5);
    lv_img_set_src(ui_Image1, &ui_img_gemini_generated_image_fdcqbnfdcqbnfdcq_png);
    lv_obj_set_width(ui_Image1, LV_SIZE_CONTENT);   /// 650
    lv_obj_set_height(ui_Image1, LV_SIZE_CONTENT);    /// 650
    lv_obj_set_x(ui_Image1, 0);
    lv_obj_set_y(ui_Image1, 10);
    lv_obj_set_align(ui_Image1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image1, 330);

    ui_alti_arc2 = lv_arc_create(ui_Screen5);
    lv_obj_set_width(ui_alti_arc2, 480);
    lv_obj_set_height(ui_alti_arc2, 480);
    lv_obj_set_x(ui_alti_arc2, -10);
    lv_obj_set_y(ui_alti_arc2, 0);
    lv_obj_set_align(ui_alti_arc2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_alti_arc2, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_arc_set_value(ui_alti_arc2, 100);
    lv_arc_set_bg_angles(ui_alti_arc2, 55, 125);
    lv_arc_set_rotation(ui_alti_arc2, 270);
    lv_obj_set_style_arc_color(ui_alti_arc2, lv_color_hex(0x103C5A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_alti_arc2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_alti_arc2, 12, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_alti_arc2, lv_color_hex(0xFF8920), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_alti_arc2, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_alti_arc2, 12, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_alti_arc2, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_alti_arc2, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_press_arc3 = lv_arc_create(ui_Screen5);
    lv_obj_set_width(ui_press_arc3, 480);
    lv_obj_set_height(ui_press_arc3, 480);
    lv_obj_set_x(ui_press_arc3, 0);
    lv_obj_set_y(ui_press_arc3, 10);
    lv_obj_set_align(ui_press_arc3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_press_arc3, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_arc_set_value(ui_press_arc3, 100);
    lv_arc_set_bg_angles(ui_press_arc3, 325, 35);
    lv_arc_set_rotation(ui_press_arc3, 270);
    lv_obj_set_style_arc_color(ui_press_arc3, lv_color_hex(0x103C5A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_press_arc3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_press_arc3, 12, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_press_arc3, lv_color_hex(0x2B80D9), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_press_arc3, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_press_arc3, 12, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_press_arc3, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_press_arc3, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_temp_arc4 = lv_arc_create(ui_Screen5);
    lv_obj_set_width(ui_temp_arc4, 480);
    lv_obj_set_height(ui_temp_arc4, 480);
    lv_obj_set_x(ui_temp_arc4, 10);
    lv_obj_set_y(ui_temp_arc4, 0);
    lv_obj_set_align(ui_temp_arc4, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_temp_arc4, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_arc_set_value(ui_temp_arc4, 100);
    lv_arc_set_bg_angles(ui_temp_arc4, 235, 305);
    lv_arc_set_rotation(ui_temp_arc4, 270);
    lv_obj_set_style_arc_color(ui_temp_arc4, lv_color_hex(0x103C5A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_temp_arc4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_temp_arc4, 12, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_temp_arc4, lv_color_hex(0xCCD9E1), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_temp_arc4, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_temp_arc4, 12, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_temp_arc4, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_temp_arc4, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_hum_arc5 = lv_arc_create(ui_Screen5);
    lv_obj_set_width(ui_hum_arc5, 480);
    lv_obj_set_height(ui_hum_arc5, 480);
    lv_obj_set_x(ui_hum_arc5, 0);
    lv_obj_set_y(ui_hum_arc5, -10);
    lv_obj_set_align(ui_hum_arc5, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_hum_arc5, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_arc_set_value(ui_hum_arc5, 100);
    lv_arc_set_bg_angles(ui_hum_arc5, 145, 215);
    lv_arc_set_rotation(ui_hum_arc5, 270);
    lv_obj_set_style_arc_color(ui_hum_arc5, lv_color_hex(0x103C5A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_hum_arc5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_hum_arc5, 12, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_shadow_color(ui_hum_arc5, lv_color_hex(0x000000), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_hum_arc5, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_hum_arc5, 100, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_hum_arc5, 50, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_color(ui_hum_arc5, lv_color_hex(0x18EBE3), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_hum_arc5, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_hum_arc5, 12, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_hum_arc5, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_hum_arc5, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_alti = lv_img_create(ui_Screen5);
    lv_img_set_src(ui_alti, &ui_img_altitude_png);
    lv_obj_set_width(ui_alti, LV_SIZE_CONTENT);   /// 64
    lv_obj_set_height(ui_alti, LV_SIZE_CONTENT);    /// 64
    lv_obj_set_x(ui_alti, 141);
    lv_obj_set_y(ui_alti, -37);
    lv_obj_set_align(ui_alti, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_alti, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_alti, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_hum = lv_img_create(ui_Screen5);
    lv_img_set_src(ui_hum, &ui_img_hum_png);
    lv_obj_set_width(ui_hum, LV_SIZE_CONTENT);   /// 64
    lv_obj_set_height(ui_hum, LV_SIZE_CONTENT);    /// 64
    lv_obj_set_x(ui_hum, -1);
    lv_obj_set_y(ui_hum, 62);
    lv_obj_set_align(ui_hum, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_hum, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_hum, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_press = lv_img_create(ui_Screen5);
    lv_img_set_src(ui_press, &ui_img_press_png);
    lv_obj_set_width(ui_press, LV_SIZE_CONTENT);   /// 64
    lv_obj_set_height(ui_press, LV_SIZE_CONTENT);    /// 64
    lv_obj_set_x(ui_press, -2);
    lv_obj_set_y(ui_press, -183);
    lv_obj_set_align(ui_press, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_press, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_press, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_temp = lv_img_create(ui_Screen5);
    lv_img_set_src(ui_temp, &ui_img_temp_png);
    lv_obj_set_width(ui_temp, LV_SIZE_CONTENT);   /// 64
    lv_obj_set_height(ui_temp, LV_SIZE_CONTENT);    /// 64
    lv_obj_set_x(ui_temp, -136);
    lv_obj_set_y(ui_temp, -45);
    lv_obj_set_align(ui_temp, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_temp, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_temp, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_press_test = lv_label_create(ui_Screen5);
    lv_obj_set_width(ui_press_test, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_press_test, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_press_test, -3);
    lv_obj_set_y(ui_press_test, -100);
    lv_obj_set_align(ui_press_test, LV_ALIGN_CENTER);
    lv_label_set_text(ui_press_test, "1111.11");
    lv_obj_set_style_text_color(ui_press_test, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_press_test, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_press_test, &lv_font_montserrat_38, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_presstext2 = lv_label_create(ui_Screen5);
    lv_obj_set_width(ui_presstext2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_presstext2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_presstext2, -2);
    lv_obj_set_y(ui_presstext2, -132);
    lv_obj_set_align(ui_presstext2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_presstext2, "气压");
    lv_obj_set_style_text_color(ui_presstext2, lv_color_hex(0x2981DE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_presstext2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_presstext2, &ui_font_chinese, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_hum_test = lv_label_create(ui_Screen5);
    lv_obj_set_width(ui_hum_test, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_hum_test, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_hum_test, -5);
    lv_obj_set_y(ui_hum_test, 149);
    lv_obj_set_align(ui_hum_test, LV_ALIGN_CENTER);
    lv_label_set_text(ui_hum_test, "33.33");
    lv_obj_set_style_text_color(ui_hum_test, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_hum_test, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_hum_test, &lv_font_montserrat_38, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_humtext1 = lv_label_create(ui_Screen5);
    lv_obj_set_width(ui_humtext1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_humtext1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_humtext1, 1);
    lv_obj_set_y(ui_humtext1, 114);
    lv_obj_set_align(ui_humtext1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_humtext1, "湿度");
    lv_obj_set_style_text_color(ui_humtext1, lv_color_hex(0x18EAE6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_humtext1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_humtext1, &ui_font_chinese, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_temp_test = lv_label_create(ui_Screen5);
    lv_obj_set_width(ui_temp_test, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_temp_test, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_temp_test, -139);
    lv_obj_set_y(ui_temp_test, 40);
    lv_obj_set_align(ui_temp_test, LV_ALIGN_CENTER);
    lv_label_set_text(ui_temp_test, "11.11");
    lv_obj_set_style_text_color(ui_temp_test, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_temp_test, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_temp_test, &lv_font_montserrat_38, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_temptext = lv_label_create(ui_Screen5);
    lv_obj_set_width(ui_temptext, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_temptext, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_temptext, -136);
    lv_obj_set_y(ui_temptext, 5);
    lv_obj_set_align(ui_temptext, LV_ALIGN_CENTER);
    lv_label_set_text(ui_temptext, "温度");
    lv_obj_set_style_text_color(ui_temptext, lv_color_hex(0xCDDAE6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_temptext, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_temptext, &ui_font_chinese, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_alti_test = lv_label_create(ui_Screen5);
    lv_obj_set_width(ui_alti_test, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_alti_test, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_alti_test, 136);
    lv_obj_set_y(ui_alti_test, 40);
    lv_obj_set_align(ui_alti_test, LV_ALIGN_CENTER);
    lv_label_set_text(ui_alti_test, "11.11");
    lv_obj_set_style_text_color(ui_alti_test, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_alti_test, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_alti_test, &lv_font_montserrat_38, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_altitext = lv_label_create(ui_Screen5);
    lv_obj_set_width(ui_altitext, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_altitext, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_altitext, 140);
    lv_obj_set_y(ui_altitext, 0);
    lv_obj_set_align(ui_altitext, LV_ALIGN_CENTER);
    lv_label_set_text(ui_altitext, "海拔");
    lv_obj_set_style_text_color(ui_altitext, lv_color_hex(0xF65500), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_altitext, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_altitext, &ui_font_chinese, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Screen5, ui_event_Screen5, LV_EVENT_ALL, NULL);

}

void ui_Screen5_screen_destroy(void)
{
    if(ui_Screen5) lv_obj_del(ui_Screen5);

    // NULL screen variables
    ui_Screen5 = NULL;
    ui_Image1 = NULL;
    ui_alti_arc2 = NULL;
    ui_press_arc3 = NULL;
    ui_temp_arc4 = NULL;
    ui_hum_arc5 = NULL;
    ui_alti = NULL;
    ui_hum = NULL;
    ui_press = NULL;
    ui_temp = NULL;
    ui_press_test = NULL;
    ui_presstext2 = NULL;
    ui_hum_test = NULL;
    ui_humtext1 = NULL;
    ui_temp_test = NULL;
    ui_temptext = NULL;
    ui_alti_test = NULL;
    ui_altitext = NULL;

}
