// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: CWatch

#ifndef UI_SCREEN4_H
#define UI_SCREEN4_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen4
extern void ui_Screen4_screen_init(void);
extern void ui_Screen4_screen_destroy(void);
extern void ui_event_Screen4(lv_event_t * e);
extern lv_obj_t * ui_Screen4;
extern lv_obj_t * ui_accey;
extern lv_obj_t * ui_magz;
extern lv_obj_t * ui_accex;
extern lv_obj_t * ui_magx;
extern lv_obj_t * ui_magy;
extern lv_obj_t * ui_accez;
extern lv_obj_t * ui_gyroz;
extern lv_obj_t * ui_gyroy;
extern lv_obj_t * ui_gyrox;
extern void ui_event_env(lv_event_t * e);
extern lv_obj_t * ui_env;
extern lv_obj_t * ui_setting;
extern lv_obj_t * ui_compass;
extern lv_obj_t * ui_heart;
extern lv_obj_t * ui_light;
extern lv_obj_t * ui_Image2;
extern lv_obj_t * ui_Image3;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

