// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: CWatch

#include "../ui.h"

lv_obj_t * ui_Screen2 = NULL;
lv_obj_t * ui_Panel1 = NULL;
lv_obj_t * ui_Spinner1 = NULL;
lv_obj_t * ui_Panel2 = NULL;
lv_obj_t * ui_Panel3 = NULL;
lv_obj_t * ui_wave_image1 = NULL;
lv_obj_t * ui_wave_image2 = NULL;
lv_obj_t * ui_Panel5 = NULL;
lv_obj_t * ui_heart_image2 = NULL;
lv_obj_t * ui_heart_rate = NULL;
lv_obj_t * ui_bpm = NULL;
lv_obj_t * ui_measuring = NULL;
// event funtions
void ui_event_Screen2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SCREEN_LOAD_START) {
        blood1_Animation(ui_wave_image2, 0);
        blood2_Animation(ui_wave_image1, 0);
        heart_Animation(ui_heart_image2, 0);
        button_Animation(ui_Panel5, 0);
        top_Animation(ui_Panel2, 0);
        opa_Animation(ui_Spinner1, 0);
        opa_Animation(ui_Panel1, 0);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_FADE_ON, 350, 0, &ui_Screen1_screen_init);
    }
}

// build funtions

void ui_Screen2_screen_init(void)
{
    ui_Screen2 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen2, lv_color_hex(0x000400), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel1 = lv_obj_create(ui_Screen2);
    lv_obj_set_width(ui_Panel1, 433);
    lv_obj_set_height(ui_Panel1, 333);
    lv_obj_set_x(ui_Panel1, -2);
    lv_obj_set_y(ui_Panel1, 100);
    lv_obj_set_align(ui_Panel1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel1, lv_color_hex(0x000400), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Panel1, lv_color_hex(0x000400), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Spinner1 = lv_spinner_create(ui_Screen2, 1000, 90);
    lv_obj_set_width(ui_Spinner1, 200);
    lv_obj_set_height(ui_Spinner1, 200);
    lv_obj_set_x(ui_Spinner1, 0);
    lv_obj_set_y(ui_Spinner1, -60);
    lv_obj_set_align(ui_Spinner1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Spinner1, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_obj_set_scrollbar_mode(ui_Spinner1, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_arc_color(ui_Spinner1, lv_color_hex(0x414441), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_Spinner1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_Spinner1, 6, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_Spinner1, lv_color_hex(0xEE1C18), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_Spinner1, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_Spinner1, 6, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_Panel2 = lv_obj_create(ui_Screen2);
    lv_obj_set_width(ui_Panel2, 150);
    lv_obj_set_height(ui_Panel2, 150);
    lv_obj_set_x(ui_Panel2, 0);
    lv_obj_set_y(ui_Panel2, -60);
    lv_obj_set_align(ui_Panel2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel2, 160, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel2, lv_color_hex(0x390800), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_clip_corner(ui_Panel2, true, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel2, lv_color_hex(0x390800), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_Panel2, lv_color_hex(0x5A2429), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_Panel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_Panel2, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_Panel2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel3 = lv_obj_create(ui_Panel2);
    lv_obj_set_width(ui_Panel3, 191);
    lv_obj_set_height(ui_Panel3, 75);
    lv_obj_set_x(ui_Panel3, 0);
    lv_obj_set_y(ui_Panel3, 37);
    lv_obj_set_align(ui_Panel3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel3, lv_color_hex(0xDE5D52), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Panel3, lv_color_hex(0xDE1810), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Panel3, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_wave_image1 = lv_img_create(ui_Panel2);
    lv_img_set_src(ui_wave_image1, &ui_img_wave2_png);
    lv_obj_set_width(ui_wave_image1, 766);
    lv_obj_set_height(ui_wave_image1, 24);
    lv_obj_set_x(ui_wave_image1, -76);
    lv_obj_set_y(ui_wave_image1, -12);
    lv_obj_set_align(ui_wave_image1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_wave_image1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_wave_image1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_wave_image2 = lv_img_create(ui_Panel2);
    lv_img_set_src(ui_wave_image2, &ui_img_wave1_png);
    lv_obj_set_width(ui_wave_image2, 505);
    lv_obj_set_height(ui_wave_image2, 24);
    lv_obj_set_x(ui_wave_image2, 30);
    lv_obj_set_y(ui_wave_image2, -12);
    lv_obj_set_align(ui_wave_image2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_wave_image2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_wave_image2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel5 = lv_obj_create(ui_Screen2);
    lv_obj_set_width(ui_Panel5, 382);
    lv_obj_set_height(ui_Panel5, 181);
    lv_obj_set_x(ui_Panel5, 10);
    lv_obj_set_y(ui_Panel5, 137);
    lv_obj_set_align(ui_Panel5, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel5, lv_color_hex(0x000400), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Panel5, lv_color_hex(0x000400), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel5, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_heart_image2 = lv_img_create(ui_Panel5);
    lv_img_set_src(ui_heart_image2, &ui_img_heart_png);
    lv_obj_set_width(ui_heart_image2, LV_SIZE_CONTENT);   /// 24
    lv_obj_set_height(ui_heart_image2, LV_SIZE_CONTENT);    /// 20
    lv_obj_set_x(ui_heart_image2, -60);
    lv_obj_set_y(ui_heart_image2, 0);
    lv_obj_set_align(ui_heart_image2, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_heart_image2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_heart_image2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_heart_image2, 300);

    ui_heart_rate = lv_label_create(ui_Panel5);
    lv_obj_set_width(ui_heart_rate, 51);
    lv_obj_set_height(ui_heart_rate, 34);
    lv_obj_set_x(ui_heart_rate, -8);
    lv_obj_set_y(ui_heart_rate, -6);
    lv_obj_set_align(ui_heart_rate, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_heart_rate, "63");
    lv_obj_set_style_text_color(ui_heart_rate, lv_color_hex(0xFBFAFB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_heart_rate, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_heart_rate, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_heart_rate, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_heart_rate, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_bpm = lv_label_create(ui_Panel5);
    lv_obj_set_width(ui_bpm, 51);
    lv_obj_set_height(ui_bpm, 23);
    lv_obj_set_x(ui_bpm, 39);
    lv_obj_set_y(ui_bpm, 0);
    lv_obj_set_align(ui_bpm, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_bpm, "bpm");
    lv_obj_set_style_text_color(ui_bpm, lv_color_hex(0xFBFAFB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_bpm, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_bpm, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_measuring = lv_label_create(ui_Panel5);
    lv_obj_set_width(ui_measuring, 227);
    lv_obj_set_height(ui_measuring, 29);
    lv_obj_set_x(ui_measuring, -8);
    lv_obj_set_y(ui_measuring, -16);
    lv_obj_set_align(ui_measuring, LV_ALIGN_CENTER);
    lv_label_set_text(ui_measuring, "        Measuring...");
    lv_obj_set_style_text_color(ui_measuring, lv_color_hex(0x6A6D6A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_measuring, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_measuring, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_measuring, lv_color_hex(0x595B59), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_measuring, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_measuring, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_measuring, LV_BORDER_SIDE_TOP, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Screen2, ui_event_Screen2, LV_EVENT_ALL, NULL);

}

void ui_Screen2_screen_destroy(void)
{
    if(ui_Screen2) lv_obj_del(ui_Screen2);

    // NULL screen variables
    ui_Screen2 = NULL;
    ui_Panel1 = NULL;
    ui_Spinner1 = NULL;
    ui_Panel2 = NULL;
    ui_Panel3 = NULL;
    ui_wave_image1 = NULL;
    ui_wave_image2 = NULL;
    ui_Panel5 = NULL;
    ui_heart_image2 = NULL;
    ui_heart_rate = NULL;
    ui_bpm = NULL;
    ui_measuring = NULL;

}
