// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: CWatch

#ifndef UI_SCREEN5_H
#define UI_SCREEN5_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen5
extern void ui_Screen5_screen_init(void);
extern void ui_Screen5_screen_destroy(void);
extern void ui_event_Screen5(lv_event_t * e);
extern lv_obj_t * ui_Screen5;
extern lv_obj_t * ui_Image1;
extern lv_obj_t * ui_alti_arc2;
extern lv_obj_t * ui_press_arc3;
extern lv_obj_t * ui_temp_arc4;
extern lv_obj_t * ui_hum_arc5;
extern lv_obj_t * ui_alti;
extern lv_obj_t * ui_hum;
extern lv_obj_t * ui_press;
extern lv_obj_t * ui_temp;
extern lv_obj_t * ui_press_test;
extern lv_obj_t * ui_presstext2;
extern lv_obj_t * ui_hum_test;
extern lv_obj_t * ui_humtext1;
extern lv_obj_t * ui_temp_test;
extern lv_obj_t * ui_temptext;
extern lv_obj_t * ui_alti_test;
extern lv_obj_t * ui_altitext;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

