// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: CWatch

#include "../ui.h"

lv_obj_t * ui_Screen4 = NULL;
lv_obj_t * ui_accey = NULL;
lv_obj_t * ui_magz = NULL;
lv_obj_t * ui_accex = NULL;
lv_obj_t * ui_magx = NULL;
lv_obj_t * ui_magy = NULL;
lv_obj_t * ui_accez = NULL;
lv_obj_t * ui_gyroz = NULL;
lv_obj_t * ui_gyroy = NULL;
lv_obj_t * ui_gyrox = NULL;
lv_obj_t * ui_env = NULL;
lv_obj_t * ui_setting = NULL;
lv_obj_t * ui_compass = NULL;
lv_obj_t * ui_heart = NULL;
lv_obj_t * ui_light = NULL;
lv_obj_t * ui_Image2 = NULL;
lv_obj_t * ui_Image3 = NULL;
// event funtions
void ui_event_Screen4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_FADE_OUT, 350, 0, &ui_Screen1_screen_init);
    }
}

void ui_event_env(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen5, LV_SCR_LOAD_ANIM_FADE_OUT, 300, 0, &ui_Screen5_screen_init);
    }
}

// build funtions

void ui_Screen4_screen_init(void)
{
    ui_Screen4 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen4, lv_color_hex(0x000400), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_accey = lv_label_create(ui_Screen4);
    lv_obj_set_width(ui_accey, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_accey, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_accey, 4);
    lv_obj_set_y(ui_accey, 50);
    lv_obj_set_align(ui_accey, LV_ALIGN_CENTER);
    lv_obj_set_style_text_color(ui_accey, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_accey, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_accey, &lv_font_montserrat_38, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_magz = lv_label_create(ui_Screen4);
    lv_obj_set_width(ui_magz, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_magz, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_magz, 110);
    lv_obj_set_y(ui_magz, -12);
    lv_obj_set_align(ui_magz, LV_ALIGN_CENTER);
    lv_obj_set_style_text_color(ui_magz, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_magz, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_magz, &lv_font_montserrat_38, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_accex = lv_label_create(ui_Screen4);
    lv_obj_set_width(ui_accex, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_accex, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_accex, -105);
    lv_obj_set_y(ui_accex, 50);
    lv_obj_set_align(ui_accex, LV_ALIGN_CENTER);
    lv_obj_set_style_text_color(ui_accex, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_accex, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_accex, &lv_font_montserrat_38, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_magx = lv_label_create(ui_Screen4);
    lv_obj_set_width(ui_magx, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_magx, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_magx, -108);
    lv_obj_set_y(ui_magx, -12);
    lv_obj_set_align(ui_magx, LV_ALIGN_CENTER);
    lv_obj_set_style_text_color(ui_magx, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_magx, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_magx, &lv_font_montserrat_38, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_magy = lv_label_create(ui_Screen4);
    lv_obj_set_width(ui_magy, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_magy, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_magy, 1);
    lv_obj_set_y(ui_magy, -3);
    lv_obj_set_align(ui_magy, LV_ALIGN_CENTER);
    lv_obj_set_style_text_color(ui_magy, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_magy, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_magy, &lv_font_montserrat_38, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_accez = lv_label_create(ui_Screen4);
    lv_obj_set_width(ui_accez, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_accez, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_accez, 116);
    lv_obj_set_y(ui_accez, 51);
    lv_obj_set_align(ui_accez, LV_ALIGN_CENTER);
    lv_obj_set_style_text_color(ui_accez, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_accez, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_accez, &lv_font_montserrat_38, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_gyroz = lv_label_create(ui_Screen4);
    lv_obj_set_width(ui_gyroz, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_gyroz, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_gyroz, 114);
    lv_obj_set_y(ui_gyroz, 122);
    lv_obj_set_align(ui_gyroz, LV_ALIGN_CENTER);
    lv_obj_set_style_text_color(ui_gyroz, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_gyroz, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_gyroz, &lv_font_montserrat_38, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_gyroy = lv_label_create(ui_Screen4);
    lv_obj_set_width(ui_gyroy, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_gyroy, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_gyroy, 6);
    lv_obj_set_y(ui_gyroy, 117);
    lv_obj_set_align(ui_gyroy, LV_ALIGN_CENTER);
    lv_obj_set_style_text_color(ui_gyroy, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_gyroy, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_gyroy, &lv_font_montserrat_38, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_gyrox = lv_label_create(ui_Screen4);
    lv_obj_set_width(ui_gyrox, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_gyrox, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_gyrox, -105);
    lv_obj_set_y(ui_gyrox, 114);
    lv_obj_set_align(ui_gyrox, LV_ALIGN_CENTER);
    lv_obj_set_style_text_color(ui_gyrox, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_gyrox, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_gyrox, &lv_font_montserrat_38, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_env = lv_imgbtn_create(ui_Screen4);
    lv_imgbtn_set_src(ui_env, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_env_png, NULL);
    lv_obj_set_width(ui_env, 64);
    lv_obj_set_height(ui_env, 64);
    lv_obj_set_x(ui_env, 4);
    lv_obj_set_y(ui_env, -174);
    lv_obj_set_align(ui_env, LV_ALIGN_CENTER);

    ui_setting = lv_img_create(ui_Screen4);
    lv_img_set_src(ui_setting, &ui_img_setting_png);
    lv_obj_set_width(ui_setting, LV_SIZE_CONTENT);   /// 64
    lv_obj_set_height(ui_setting, LV_SIZE_CONTENT);    /// 64
    lv_obj_set_x(ui_setting, 4);
    lv_obj_set_y(ui_setting, -85);
    lv_obj_set_align(ui_setting, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_setting, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_setting, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_compass = lv_img_create(ui_Screen4);
    lv_img_set_src(ui_compass, &ui_img_compass_png);
    lv_obj_set_width(ui_compass, LV_SIZE_CONTENT);   /// 64
    lv_obj_set_height(ui_compass, LV_SIZE_CONTENT);    /// 64
    lv_obj_set_x(ui_compass, 107);
    lv_obj_set_y(ui_compass, -86);
    lv_obj_set_align(ui_compass, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_compass, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_compass, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_heart = lv_img_create(ui_Screen4);
    lv_img_set_src(ui_heart, &ui_img_heart1_png);
    lv_obj_set_width(ui_heart, LV_SIZE_CONTENT);   /// 64
    lv_obj_set_height(ui_heart, LV_SIZE_CONTENT);    /// 64
    lv_obj_set_x(ui_heart, -107);
    lv_obj_set_y(ui_heart, -87);
    lv_obj_set_align(ui_heart, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_heart, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_heart, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_light = lv_img_create(ui_Screen4);
    lv_img_set_src(ui_light, &ui_img_light_png);
    lv_obj_set_width(ui_light, LV_SIZE_CONTENT);   /// 64
    lv_obj_set_height(ui_light, LV_SIZE_CONTENT);    /// 64
    lv_obj_set_x(ui_light, 3);
    lv_obj_set_y(ui_light, 171);
    lv_obj_set_align(ui_light, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_light, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_light, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image2 = lv_img_create(ui_Screen4);
    lv_img_set_src(ui_Image2, &ui_img_wrain_png);
    lv_obj_set_width(ui_Image2, LV_SIZE_CONTENT);   /// 200
    lv_obj_set_height(ui_Image2, LV_SIZE_CONTENT);    /// 200
    lv_obj_set_x(ui_Image2, -109);
    lv_obj_set_y(ui_Image2, 30);
    lv_obj_set_align(ui_Image2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image3 = lv_img_create(ui_Screen4);
    lv_img_set_src(ui_Image3, &ui_img_wcloud_png);
    lv_obj_set_width(ui_Image3, LV_SIZE_CONTENT);   /// 256
    lv_obj_set_height(ui_Image3, LV_SIZE_CONTENT);    /// 256
    lv_obj_set_x(ui_Image3, 113);
    lv_obj_set_y(ui_Image3, 13);
    lv_obj_set_align(ui_Image3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_env, ui_event_env, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Screen4, ui_event_Screen4, LV_EVENT_ALL, NULL);

}

void ui_Screen4_screen_destroy(void)
{
    if(ui_Screen4) lv_obj_del(ui_Screen4);

    // NULL screen variables
    ui_Screen4 = NULL;
    ui_accey = NULL;
    ui_magz = NULL;
    ui_accex = NULL;
    ui_magx = NULL;
    ui_magy = NULL;
    ui_accez = NULL;
    ui_gyroz = NULL;
    ui_gyroy = NULL;
    ui_gyrox = NULL;
    ui_env = NULL;
    ui_setting = NULL;
    ui_compass = NULL;
    ui_heart = NULL;
    ui_light = NULL;
    ui_Image2 = NULL;
    ui_Image3 = NULL;

}
