// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: CWatch

#include "../ui.h"

lv_obj_t * ui_Screen1 = NULL;
lv_obj_t * ui_step_arc = NULL;
lv_obj_t * ui_hot_arc = NULL;
lv_obj_t * ui_battery_arc = NULL;
lv_obj_t * ui_battery_label = NULL;
lv_obj_t * ui_battery_slider = NULL;
lv_obj_t * ui_battery_image = NULL;
lv_obj_t * ui_button2 = NULL;
lv_obj_t * ui_heart_arc = NULL;
lv_obj_t * ui_heart_label = NULL;
lv_obj_t * ui_heart_image1 = NULL;
lv_obj_t * ui_heart_button = NULL;
lv_obj_t * ui_Arc9 = NULL;
lv_obj_t * ui_button = NULL;
lv_obj_t * ui_weather_icon = NULL;
lv_obj_t * ui_maintemp = NULL;
lv_obj_t * ui_spo2_arc = NULL;
lv_obj_t * ui_spo2_label = NULL;
lv_obj_t * ui_spo2_image = NULL;
lv_obj_t * ui_spo2_button = NULL;
lv_obj_t * ui_time = NULL;
lv_obj_t * ui_step_image = NULL;
lv_obj_t * ui_step_label = NULL;
lv_obj_t * ui_hot_image = NULL;
lv_obj_t * ui_hot_label = NULL;
lv_obj_t * ui_week = NULL;
lv_obj_t * ui_hour = NULL;
lv_obj_t * ui_min = NULL;
lv_obj_t * ui_day = NULL;
lv_obj_t * ui_date = NULL;
lv_obj_t * ui_year = NULL;
lv_obj_t * ui_month = NULL;
// event funtions
void ui_event_button2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen6, LV_SCR_LOAD_ANIM_FADE_OUT, 350, 0, &ui_Screen6_screen_init);
    }
}

void ui_event_heart_button(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen2, LV_SCR_LOAD_ANIM_FADE_OUT, 350, 0, &ui_Screen2_screen_init);
    }
}

void ui_event_button(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_weather, LV_SCR_LOAD_ANIM_FADE_OUT, 350, 0, &ui_weather_screen_init);
    }
}

void ui_event_spo2_button(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen3, LV_SCR_LOAD_ANIM_FADE_OUT, 500, 0, &ui_Screen3_screen_init);
    }
}

// build funtions

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_step_arc = lv_arc_create(ui_Screen1);
    lv_obj_set_width(ui_step_arc, 420);
    lv_obj_set_height(ui_step_arc, 420);
    lv_obj_set_align(ui_step_arc, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_step_arc, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_arc_set_value(ui_step_arc, 25);
    lv_arc_set_bg_angles(ui_step_arc, 15, 65);
    lv_arc_set_rotation(ui_step_arc, 270);
    lv_obj_set_style_arc_color(ui_step_arc, lv_color_hex(0x103C5A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_step_arc, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_step_arc, 12, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_step_arc, lv_color_hex(0x2999E6), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_step_arc, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_step_arc, 12, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_step_arc, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_step_arc, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_hot_arc = lv_arc_create(ui_Screen1);
    lv_obj_set_width(ui_hot_arc, 420);
    lv_obj_set_height(ui_hot_arc, 420);
    lv_obj_set_align(ui_hot_arc, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_hot_arc, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_arc_set_value(ui_hot_arc, 20);
    lv_arc_set_bg_angles(ui_hot_arc, 115, 165);
    lv_arc_set_mode(ui_hot_arc, LV_ARC_MODE_REVERSE);
    lv_arc_set_rotation(ui_hot_arc, 270);
    lv_obj_set_style_arc_color(ui_hot_arc, lv_color_hex(0x623000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_hot_arc, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_hot_arc, 12, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_hot_arc, lv_color_hex(0xFA8109), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_hot_arc, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_hot_arc, 12, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_hot_arc, true, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_hot_arc, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_hot_arc, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_battery_arc = lv_arc_create(ui_Screen1);
    lv_obj_set_width(ui_battery_arc, 100);
    lv_obj_set_height(ui_battery_arc, 100);
    lv_obj_set_x(ui_battery_arc, -45);
    lv_obj_set_y(ui_battery_arc, 160);
    lv_obj_set_align(ui_battery_arc, LV_ALIGN_CENTER);
    lv_arc_set_range(ui_battery_arc, 0, 10);
    lv_arc_set_value(ui_battery_arc, 10);
    lv_arc_set_bg_angles(ui_battery_arc, -105, 270);
    lv_obj_set_style_arc_color(ui_battery_arc, lv_color_hex(0x31C618), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_battery_arc, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_battery_arc, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_battery_arc, lv_color_hex(0x30C51A), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_battery_arc, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_battery_arc, 5, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_battery_arc, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_battery_arc, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_battery_label = lv_label_create(ui_battery_arc);
    lv_obj_set_width(ui_battery_label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_battery_label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_battery_label, 0);
    lv_obj_set_y(ui_battery_label, 25);
    lv_obj_set_align(ui_battery_label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_battery_label, "88%");
    lv_obj_set_style_text_color(ui_battery_label, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_battery_label, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_battery_label, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_battery_slider = lv_slider_create(ui_battery_arc);
    lv_slider_set_range(ui_battery_slider, 0, 10);
    lv_slider_set_value(ui_battery_slider, 8, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_battery_slider) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_battery_slider, 0,
                                                                                                   LV_ANIM_OFF);
    lv_obj_set_width(ui_battery_slider, 16);
    lv_obj_set_height(ui_battery_slider, 26);
    lv_obj_set_x(ui_battery_slider, 0);
    lv_obj_set_y(ui_battery_slider, -8);
    lv_obj_set_align(ui_battery_slider, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_battery_slider, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_battery_slider, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_battery_slider, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_battery_slider, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_battery_slider, lv_color_hex(0x43EF26), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_battery_slider, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_battery_slider, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_battery_slider, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_battery_image = lv_img_create(ui_battery_arc);
    lv_img_set_src(ui_battery_image, &ui_img_battery_png);
    lv_obj_set_width(ui_battery_image, LV_SIZE_CONTENT);   /// 48
    lv_obj_set_height(ui_battery_image, LV_SIZE_CONTENT);    /// 48
    lv_obj_set_x(ui_battery_image, 0);
    lv_obj_set_y(ui_battery_image, -10);
    lv_obj_set_align(ui_battery_image, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_battery_image, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_battery_image, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_button2 = lv_btn_create(ui_battery_arc);
    lv_obj_set_width(ui_button2, 110);
    lv_obj_set_height(ui_button2, 110);
    lv_obj_set_x(ui_button2, 0);
    lv_obj_set_y(ui_button2, -1);
    lv_obj_set_align(ui_button2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_button2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_button2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_button2, 90, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_button2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_button2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_button2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_button2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_heart_arc = lv_arc_create(ui_Screen1);
    lv_obj_set_width(ui_heart_arc, 100);
    lv_obj_set_height(ui_heart_arc, 100);
    lv_obj_set_x(ui_heart_arc, -135);
    lv_obj_set_y(ui_heart_arc, 60);
    lv_obj_set_align(ui_heart_arc, LV_ALIGN_CENTER);
    lv_arc_set_range(ui_heart_arc, 0, 10);
    lv_arc_set_value(ui_heart_arc, 10);
    lv_arc_set_bg_angles(ui_heart_arc, -105, 270);
    lv_obj_set_style_arc_color(ui_heart_arc, lv_color_hex(0xF62000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_heart_arc, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_heart_arc, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_heart_arc, lv_color_hex(0xF52105), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_heart_arc, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_heart_arc, 5, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_heart_arc, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_heart_arc, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_heart_label = lv_label_create(ui_heart_arc);
    lv_obj_set_width(ui_heart_label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_heart_label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_heart_label, 0);
    lv_obj_set_y(ui_heart_label, -10);
    lv_obj_set_align(ui_heart_label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_heart_label, "88");
    lv_obj_set_style_text_color(ui_heart_label, lv_color_hex(0xF52000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_heart_label, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_heart_label, &lv_font_montserrat_38, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_heart_image1 = lv_img_create(ui_heart_arc);
    lv_img_set_src(ui_heart_image1, &ui_img_1883903296);
    lv_obj_set_width(ui_heart_image1, LV_SIZE_CONTENT);   /// 32
    lv_obj_set_height(ui_heart_image1, LV_SIZE_CONTENT);    /// 32
    lv_obj_set_x(ui_heart_image1, 0);
    lv_obj_set_y(ui_heart_image1, 25);
    lv_obj_set_align(ui_heart_image1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_heart_image1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_heart_image1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_heart_button = lv_btn_create(ui_heart_arc);
    lv_obj_set_width(ui_heart_button, 110);
    lv_obj_set_height(ui_heart_button, 110);
    lv_obj_set_align(ui_heart_button, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_heart_button, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_heart_button, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_heart_button, 90, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_heart_button, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_heart_button, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_heart_button, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_heart_button, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Arc9 = lv_arc_create(ui_Screen1);
    lv_obj_set_width(ui_Arc9, 100);
    lv_obj_set_height(ui_Arc9, 100);
    lv_obj_set_x(ui_Arc9, -45);
    lv_obj_set_y(ui_Arc9, -160);
    lv_obj_set_align(ui_Arc9, LV_ALIGN_CENTER);
    lv_arc_set_range(ui_Arc9, 0, 10);
    lv_arc_set_value(ui_Arc9, 10);
    lv_arc_set_bg_angles(ui_Arc9, -105, 270);
    lv_obj_set_style_arc_color(ui_Arc9, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_Arc9, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_Arc9, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_Arc9, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_Arc9, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_Arc9, 5, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Arc9, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Arc9, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_button = lv_btn_create(ui_Arc9);
    lv_obj_set_width(ui_button, 110);
    lv_obj_set_height(ui_button, 110);
    lv_obj_set_align(ui_button, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_button, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_button, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_button, 90, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_button, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_button, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_button, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_button, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_weather_icon = lv_img_create(ui_Arc9);
    lv_img_set_src(ui_weather_icon, &ui_img_weather_rain_png);
    lv_obj_set_width(ui_weather_icon, LV_SIZE_CONTENT);   /// 37
    lv_obj_set_height(ui_weather_icon, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_x(ui_weather_icon, 0);
    lv_obj_set_y(ui_weather_icon, -20);
    lv_obj_set_align(ui_weather_icon, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_weather_icon, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_weather_icon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_maintemp = lv_label_create(ui_Arc9);
    lv_obj_set_width(ui_maintemp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_maintemp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_maintemp, 6);
    lv_obj_set_y(ui_maintemp, 16);
    lv_obj_set_align(ui_maintemp, LV_ALIGN_CENTER);
    lv_label_set_text(ui_maintemp, "39°");
    lv_obj_set_style_text_color(ui_maintemp, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_maintemp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_maintemp, &lv_font_montserrat_38, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_spo2_arc = lv_arc_create(ui_Screen1);
    lv_obj_set_width(ui_spo2_arc, 100);
    lv_obj_set_height(ui_spo2_arc, 100);
    lv_obj_set_x(ui_spo2_arc, -135);
    lv_obj_set_y(ui_spo2_arc, -60);
    lv_obj_set_align(ui_spo2_arc, LV_ALIGN_CENTER);
    lv_arc_set_range(ui_spo2_arc, 0, 10);
    lv_arc_set_value(ui_spo2_arc, 10);
    lv_arc_set_bg_angles(ui_spo2_arc, -105, 270);
    lv_obj_set_style_arc_color(ui_spo2_arc, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_spo2_arc, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_spo2_arc, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_spo2_arc, lv_color_hex(0xFF0000), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_spo2_arc, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_spo2_arc, 5, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_spo2_arc, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_spo2_arc, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_spo2_label = lv_label_create(ui_spo2_arc);
    lv_obj_set_width(ui_spo2_label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_spo2_label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_spo2_label, 0);
    lv_obj_set_y(ui_spo2_label, -10);
    lv_obj_set_align(ui_spo2_label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_spo2_label, "88");
    lv_obj_set_style_text_color(ui_spo2_label, lv_color_hex(0xF62000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_spo2_label, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_spo2_label, &lv_font_montserrat_38, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_spo2_image = lv_img_create(ui_spo2_arc);
    lv_img_set_src(ui_spo2_image, &ui_img_o2_png);
    lv_obj_set_width(ui_spo2_image, LV_SIZE_CONTENT);   /// 32
    lv_obj_set_height(ui_spo2_image, LV_SIZE_CONTENT);    /// 32
    lv_obj_set_x(ui_spo2_image, 3);
    lv_obj_set_y(ui_spo2_image, 25);
    lv_obj_set_align(ui_spo2_image, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_spo2_image, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_spo2_image, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_spo2_button = lv_btn_create(ui_spo2_arc);
    lv_obj_set_width(ui_spo2_button, 110);
    lv_obj_set_height(ui_spo2_button, 110);
    lv_obj_set_align(ui_spo2_button, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_spo2_button, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_spo2_button, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_spo2_button, 90, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_spo2_button, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_spo2_button, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_spo2_button, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_spo2_button, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_time = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_time, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_time, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_time, 55);
    lv_obj_set_y(ui_time, -25);
    lv_obj_set_align(ui_time, LV_ALIGN_CENTER);
    lv_label_set_text(ui_time, ":");
    lv_obj_set_style_text_color(ui_time, lv_color_hex(0xF9F9F9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_time, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_time, &ui_font_large, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_step_image = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_step_image, &ui_img_foot_png);
    lv_obj_set_width(ui_step_image, LV_SIZE_CONTENT);   /// 42
    lv_obj_set_height(ui_step_image, LV_SIZE_CONTENT);    /// 32
    lv_obj_set_x(ui_step_image, 100);
    lv_obj_set_y(ui_step_image, -140);
    lv_obj_set_align(ui_step_image, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_step_image, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_step_image, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_step_label = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_step_label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_step_label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_step_label, 100);
    lv_obj_set_y(ui_step_label, -110);
    lv_obj_set_align(ui_step_label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_step_label, "6666");
    lv_obj_set_style_text_color(ui_step_label, lv_color_hex(0x2999E6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_step_label, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_step_label, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_hot_image = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_hot_image, &ui_img_hot_png);
    lv_obj_set_width(ui_hot_image, LV_SIZE_CONTENT);   /// 32
    lv_obj_set_height(ui_hot_image, LV_SIZE_CONTENT);    /// 32
    lv_obj_set_x(ui_hot_image, 100);
    lv_obj_set_y(ui_hot_image, 115);
    lv_obj_set_align(ui_hot_image, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_hot_image, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_hot_image, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_hot_label = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_hot_label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_hot_label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_hot_label, 100);
    lv_obj_set_y(ui_hot_label, 145);
    lv_obj_set_align(ui_hot_label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_hot_label, "6666");
    lv_obj_set_style_text_color(ui_hot_label, lv_color_hex(0xFF8108), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_hot_label, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_hot_label, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_week = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_week, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_week, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_week, 132);
    lv_obj_set_y(ui_week, 34);
    lv_obj_set_align(ui_week, LV_ALIGN_CENTER);
    lv_label_set_text(ui_week, "周一");
    lv_obj_set_style_text_color(ui_week, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_week, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_week, &ui_font_chinese, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_hour = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_hour, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_hour, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_hour, 9);
    lv_obj_set_y(ui_hour, -18);
    lv_obj_set_align(ui_hour, LV_ALIGN_CENTER);
    lv_label_set_text(ui_hour, "11");
    lv_obj_set_style_text_color(ui_hour, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_hour, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_hour, &ui_font_large, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_min = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_min, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_min, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_min, 104);
    lv_obj_set_y(ui_min, -18);
    lv_obj_set_align(ui_min, LV_ALIGN_CENTER);
    lv_label_set_text(ui_min, "01");
    lv_obj_set_style_text_color(ui_min, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_min, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_min, &ui_font_large, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_day = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_day, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_day, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_day, 75);
    lv_obj_set_y(ui_day, 34);
    lv_obj_set_align(ui_day, LV_ALIGN_CENTER);
    lv_label_set_text(ui_day, "29");
    lv_obj_set_style_text_color(ui_day, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_day, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_day, &ui_font_chinese, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_date = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_date, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_date, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_date, 27);
    lv_obj_set_y(ui_date, 34);
    lv_obj_set_align(ui_date, LV_ALIGN_CENTER);
    lv_label_set_text(ui_date, "		/		/");
    lv_obj_set_style_text_color(ui_date, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_date, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_date, &ui_font_chinese, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_year = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_year, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_year, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_year, -12);
    lv_obj_set_y(ui_year, 34);
    lv_obj_set_align(ui_year, LV_ALIGN_CENTER);
    lv_label_set_text(ui_year, "2026");
    lv_obj_set_style_text_color(ui_year, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_year, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_year, &ui_font_chinese, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_month = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_month, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_month, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_month, 38);
    lv_obj_set_y(ui_month, 34);
    lv_obj_set_align(ui_month, LV_ALIGN_CENTER);
    lv_label_set_text(ui_month, "12");
    lv_obj_set_style_text_color(ui_month, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_month, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_month, &ui_font_chinese, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_button2, ui_event_button2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_heart_button, ui_event_heart_button, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_button, ui_event_button, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_spo2_button, ui_event_spo2_button, LV_EVENT_ALL, NULL);

}

void ui_Screen1_screen_destroy(void)
{
    if(ui_Screen1) lv_obj_del(ui_Screen1);

    // NULL screen variables
    ui_Screen1 = NULL;
    ui_step_arc = NULL;
    ui_hot_arc = NULL;
    ui_battery_arc = NULL;
    ui_battery_label = NULL;
    ui_battery_slider = NULL;
    ui_battery_image = NULL;
    ui_button2 = NULL;
    ui_heart_arc = NULL;
    ui_heart_label = NULL;
    ui_heart_image1 = NULL;
    ui_heart_button = NULL;
    ui_Arc9 = NULL;
    ui_button = NULL;
    ui_weather_icon = NULL;
    ui_maintemp = NULL;
    ui_spo2_arc = NULL;
    ui_spo2_label = NULL;
    ui_spo2_image = NULL;
    ui_spo2_button = NULL;
    ui_time = NULL;
    ui_step_image = NULL;
    ui_step_label = NULL;
    ui_hot_image = NULL;
    ui_hot_label = NULL;
    ui_week = NULL;
    ui_hour = NULL;
    ui_min = NULL;
    ui_day = NULL;
    ui_date = NULL;
    ui_year = NULL;
    ui_month = NULL;

}
