// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: CWatch

#ifndef UI_SCREEN1_H
#define UI_SCREEN1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen1
extern void ui_Screen1_screen_init(void);
extern void ui_Screen1_screen_destroy(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_step_arc;
extern lv_obj_t * ui_hot_arc;
extern lv_obj_t * ui_battery_arc;
extern lv_obj_t * ui_battery_label;
extern lv_obj_t * ui_battery_slider;
extern lv_obj_t * ui_battery_image;
extern void ui_event_button2(lv_event_t * e);
extern lv_obj_t * ui_button2;
extern lv_obj_t * ui_heart_arc;
extern lv_obj_t * ui_heart_label;
extern lv_obj_t * ui_heart_image1;
extern void ui_event_heart_button(lv_event_t * e);
extern lv_obj_t * ui_heart_button;
extern lv_obj_t * ui_Arc9;
extern void ui_event_button(lv_event_t * e);
extern lv_obj_t * ui_button;
extern lv_obj_t * ui_weather_icon;
extern lv_obj_t * ui_maintemp;
extern lv_obj_t * ui_spo2_arc;
extern lv_obj_t * ui_spo2_label;
extern lv_obj_t * ui_spo2_image;
extern void ui_event_spo2_button(lv_event_t * e);
extern lv_obj_t * ui_spo2_button;
extern lv_obj_t * ui_time;
extern lv_obj_t * ui_step_image;
extern lv_obj_t * ui_step_label;
extern lv_obj_t * ui_hot_image;
extern lv_obj_t * ui_hot_label;
extern lv_obj_t * ui_week;
extern lv_obj_t * ui_hour;
extern lv_obj_t * ui_min;
extern lv_obj_t * ui_day;
extern lv_obj_t * ui_date;
extern lv_obj_t * ui_year;
extern lv_obj_t * ui_month;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

