// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: CWatch

#ifndef UI_WEATHER_H
#define UI_WEATHER_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_weather
extern void ui_weather_screen_init(void);
extern void ui_weather_screen_destroy(void);
extern void ui_event_weather(lv_event_t * e);
extern lv_obj_t * ui_weather;
extern lv_obj_t * ui_weathertemp;
extern lv_obj_t * ui_weather_image;
extern lv_obj_t * ui_city;
extern lv_obj_t * ui_weathernow;
extern lv_obj_t * ui_weathermin;
extern lv_obj_t * ui_aqi;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

