// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: CWatch

#ifndef UI_WEATHER2_H
#define UI_WEATHER2_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_weather2
extern void ui_weather2_screen_init(void);
extern void ui_weather2_screen_destroy(void);
extern void ui_event_weather2(lv_event_t * e);
extern lv_obj_t * ui_weather2;
extern lv_obj_t * ui_Panel4;
extern lv_obj_t * ui_Panel6;
extern lv_obj_t * ui_weathertime1;
extern lv_obj_t * ui_weathertype1;
extern lv_obj_t * ui_weather_temp1;
extern lv_obj_t * ui_Panel8;
extern lv_obj_t * ui_weathertime2;
extern lv_obj_t * ui_weathertype2;
extern lv_obj_t * ui_weather_temp2;
extern lv_obj_t * ui_Panel9;
extern lv_obj_t * ui_weathertime3;
extern lv_obj_t * ui_weathertype3;
extern lv_obj_t * ui_weather_temp3;
extern lv_obj_t * ui_Panel10;
extern lv_obj_t * ui_weathertime4;
extern lv_obj_t * ui_weathertype4;
extern lv_obj_t * ui_weather_temp4;
extern lv_obj_t * ui_Panel11;
extern lv_obj_t * ui_weathertime5;
extern lv_obj_t * ui_weathertype5;
extern lv_obj_t * ui_weather_temp5;
extern lv_obj_t * ui_Panel12;
extern lv_obj_t * ui_weathertime6;
extern lv_obj_t * ui_weathertype6;
extern lv_obj_t * ui_weather_temp6;
extern lv_obj_t * ui_Panel13;
extern lv_obj_t * ui_weathertime7;
extern lv_obj_t * ui_weathertype7;
extern lv_obj_t * ui_weather_temp7;
extern lv_obj_t * ui_Panel14;
extern lv_obj_t * ui_weathertime8;
extern lv_obj_t * ui_weathertype8;
extern lv_obj_t * ui_weather_temp8;
extern lv_obj_t * ui_Panel15;
extern lv_obj_t * ui_weathertime9;
extern lv_obj_t * ui_weathertype9;
extern lv_obj_t * ui_weather_temp9;
extern lv_obj_t * ui_Panel16;
extern lv_obj_t * ui_weathertime10;
extern lv_obj_t * ui_weathertype10;
extern lv_obj_t * ui_weather_temp10;
extern lv_obj_t * ui_Panel17;
extern lv_obj_t * ui_weathertime11;
extern lv_obj_t * ui_weathertype11;
extern lv_obj_t * ui_weather_temp11;
extern lv_obj_t * ui_Panel18;
extern lv_obj_t * ui_weathertime12;
extern lv_obj_t * ui_weathertype12;
extern lv_obj_t * ui_weather_temp12;
extern lv_obj_t * ui_Panel7;
extern lv_obj_t * ui_Panel19;
extern lv_obj_t * ui_shijian1;
extern lv_obj_t * ui_weathertype13;
extern lv_obj_t * ui_weathermax1;
extern lv_obj_t * ui_Panel20;
extern lv_obj_t * ui_shijian2;
extern lv_obj_t * ui_weathertype14;
extern lv_obj_t * ui_weathermax2;
extern lv_obj_t * ui_Panel21;
extern lv_obj_t * ui_shijian3;
extern lv_obj_t * ui_weathertype15;
extern lv_obj_t * ui_weathermax3;
extern lv_obj_t * ui_Panel22;
extern lv_obj_t * ui_shijian4;
extern lv_obj_t * ui_weathertype16;
extern lv_obj_t * ui_weathermax4;
extern lv_obj_t * ui_Panel23;
extern lv_obj_t * ui_shijian5;
extern lv_obj_t * ui_weathertype17;
extern lv_obj_t * ui_weathermax5;
extern lv_obj_t * ui_Panel24;
extern lv_obj_t * ui_shijian6;
extern lv_obj_t * ui_weathertype18;
extern lv_obj_t * ui_weathermax6;
extern lv_obj_t * ui_Panel25;
extern lv_obj_t * ui_shijian7;
extern lv_obj_t * ui_weathertype19;
extern lv_obj_t * ui_weathermax7;
extern lv_obj_t * ui_city2;
extern lv_obj_t * ui_week2;
extern lv_obj_t * ui_year2;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

