// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: CWatch

#include "../ui.h"

lv_obj_t * ui_weather = NULL;
lv_obj_t * ui_weathertemp = NULL;
lv_obj_t * ui_weather_image = NULL;
lv_obj_t * ui_weathertemp1 = NULL;
lv_obj_t * ui_city = NULL;
lv_obj_t * ui_weathernow = NULL;
lv_obj_t * ui_weathermin = NULL;
lv_obj_t * ui_aqi = NULL;
// event funtions
void ui_event_weather(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_FADE_ON, 300, 0, &ui_Screen1_screen_init);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_TOP) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_weather2, LV_SCR_LOAD_ANIM_FADE_ON, 300, 0, &ui_weather2_screen_init);
    }
}

// build funtions

void ui_weather_screen_init(void)
{
    ui_weather = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_weather, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_weather, lv_color_hex(0x000400), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_weather, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_weathertemp = lv_label_create(ui_weather);
    lv_obj_set_width(ui_weathertemp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_weathertemp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_weathertemp, -97);
    lv_obj_set_y(ui_weathertemp, -10);
    lv_obj_set_align(ui_weathertemp, LV_ALIGN_CENTER);
    lv_label_set_text(ui_weathertemp, "40");
    lv_obj_set_style_text_color(ui_weathertemp, lv_color_hex(0xEE1E1E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_weathertemp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_weathertemp, &ui_font_large_promax, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_weather_image = lv_img_create(ui_weather);
    lv_img_set_src(ui_weather_image, &ui_img_wsun_png);
    lv_obj_set_width(ui_weather_image, LV_SIZE_CONTENT);   /// 262
    lv_obj_set_height(ui_weather_image, LV_SIZE_CONTENT);    /// 256
    lv_obj_set_x(ui_weather_image, 118);
    lv_obj_set_y(ui_weather_image, -33);
    lv_obj_set_align(ui_weather_image, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_weather_image, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_weather_image, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_weathertemp1 = lv_label_create(ui_weather);
    lv_obj_set_width(ui_weathertemp1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_weathertemp1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_weathertemp1, -3);
    lv_obj_set_y(ui_weathertemp1, -24);
    lv_obj_set_align(ui_weathertemp1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_weathertemp1, "°");
    lv_obj_set_style_text_color(ui_weathertemp1, lv_color_hex(0xEE1E1E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_weathertemp1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_weathertemp1, &ui_font_large_promax, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_city = lv_label_create(ui_weather);
    lv_obj_set_width(ui_city, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_city, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_city, -33);
    lv_obj_set_y(ui_city, -142);
    lv_obj_set_align(ui_city, LV_ALIGN_CENTER);
    lv_label_set_text(ui_city, "惠州");
    lv_obj_set_style_text_color(ui_city, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_city, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_city, &ui_font_chinese2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_weathernow = lv_label_create(ui_weather);
    lv_obj_set_width(ui_weathernow, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_weathernow, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_weathernow, -124);
    lv_obj_set_y(ui_weathernow, 75);
    lv_obj_set_align(ui_weathernow, LV_ALIGN_CENTER);
    lv_label_set_text(ui_weathernow, "晴");
    lv_obj_set_style_text_color(ui_weathernow, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_weathernow, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_weathernow, &ui_font_chinese, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_weathermin = lv_label_create(ui_weather);
    lv_obj_set_width(ui_weathermin, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_weathermin, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_weathermin, -56);
    lv_obj_set_y(ui_weathermin, 75);
    lv_obj_set_align(ui_weathermin, LV_ALIGN_CENTER);
    lv_label_set_text(ui_weathermin, "28°/50°");
    lv_obj_set_style_text_color(ui_weathermin, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_weathermin, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_weathermin, &ui_font_chinese, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_aqi = lv_label_create(ui_weather);
    lv_obj_set_width(ui_aqi, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_aqi, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_aqi, -83);
    lv_obj_set_y(ui_aqi, 115);
    lv_obj_set_align(ui_aqi, LV_ALIGN_CENTER);
    lv_label_set_text(ui_aqi, "100 优");
    lv_obj_set_style_text_color(ui_aqi, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_aqi, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_aqi, &ui_font_chinese, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_weather, ui_event_weather, LV_EVENT_ALL, NULL);

}

void ui_weather_screen_destroy(void)
{
    if(ui_weather) lv_obj_del(ui_weather);

    // NULL screen variables
    ui_weather = NULL;
    ui_weathertemp = NULL;
    ui_weather_image = NULL;
    ui_weathertemp1 = NULL;
    ui_city = NULL;
    ui_weathernow = NULL;
    ui_weathermin = NULL;
    ui_aqi = NULL;

}
