// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: CWatch

#include "../ui.h"

lv_obj_t * ui_weather2 = NULL;
lv_obj_t * ui_Panel4 = NULL;
lv_obj_t * ui_Panel6 = NULL;
lv_obj_t * ui_weathertime1 = NULL;
lv_obj_t * ui_weathertype1 = NULL;
lv_obj_t * ui_weather_temp1 = NULL;
lv_obj_t * ui_Panel8 = NULL;
lv_obj_t * ui_weathertime2 = NULL;
lv_obj_t * ui_weathertype2 = NULL;
lv_obj_t * ui_weather_temp2 = NULL;
lv_obj_t * ui_Panel9 = NULL;
lv_obj_t * ui_weathertime3 = NULL;
lv_obj_t * ui_weathertype3 = NULL;
lv_obj_t * ui_weather_temp3 = NULL;
lv_obj_t * ui_Panel10 = NULL;
lv_obj_t * ui_weathertime4 = NULL;
lv_obj_t * ui_weathertype4 = NULL;
lv_obj_t * ui_weather_temp4 = NULL;
lv_obj_t * ui_Panel11 = NULL;
lv_obj_t * ui_weathertime5 = NULL;
lv_obj_t * ui_weathertype5 = NULL;
lv_obj_t * ui_weather_temp5 = NULL;
lv_obj_t * ui_Panel12 = NULL;
lv_obj_t * ui_weathertime6 = NULL;
lv_obj_t * ui_weathertype6 = NULL;
lv_obj_t * ui_weather_temp6 = NULL;
lv_obj_t * ui_Panel13 = NULL;
lv_obj_t * ui_weathertime7 = NULL;
lv_obj_t * ui_weathertype7 = NULL;
lv_obj_t * ui_weather_temp7 = NULL;
lv_obj_t * ui_Panel14 = NULL;
lv_obj_t * ui_weathertime8 = NULL;
lv_obj_t * ui_weathertype8 = NULL;
lv_obj_t * ui_weather_temp8 = NULL;
lv_obj_t * ui_Panel15 = NULL;
lv_obj_t * ui_weathertime9 = NULL;
lv_obj_t * ui_weathertype9 = NULL;
lv_obj_t * ui_weather_temp9 = NULL;
lv_obj_t * ui_Panel16 = NULL;
lv_obj_t * ui_weathertime10 = NULL;
lv_obj_t * ui_weathertype10 = NULL;
lv_obj_t * ui_weather_temp10 = NULL;
lv_obj_t * ui_Panel17 = NULL;
lv_obj_t * ui_weathertime11 = NULL;
lv_obj_t * ui_weathertype11 = NULL;
lv_obj_t * ui_weather_temp11 = NULL;
lv_obj_t * ui_Panel18 = NULL;
lv_obj_t * ui_weathertime12 = NULL;
lv_obj_t * ui_weathertype12 = NULL;
lv_obj_t * ui_weather_temp12 = NULL;
lv_obj_t * ui_Panel7 = NULL;
lv_obj_t * ui_Panel19 = NULL;
lv_obj_t * ui_shijian1 = NULL;
lv_obj_t * ui_weathertype13 = NULL;
lv_obj_t * ui_weathermax1 = NULL;
lv_obj_t * ui_Panel20 = NULL;
lv_obj_t * ui_shijian2 = NULL;
lv_obj_t * ui_weathertype14 = NULL;
lv_obj_t * ui_weathermax2 = NULL;
lv_obj_t * ui_Panel21 = NULL;
lv_obj_t * ui_shijian3 = NULL;
lv_obj_t * ui_weathertype15 = NULL;
lv_obj_t * ui_weathermax3 = NULL;
lv_obj_t * ui_Panel22 = NULL;
lv_obj_t * ui_shijian4 = NULL;
lv_obj_t * ui_weathertype16 = NULL;
lv_obj_t * ui_weathermax4 = NULL;
lv_obj_t * ui_Panel23 = NULL;
lv_obj_t * ui_shijian5 = NULL;
lv_obj_t * ui_weathertype17 = NULL;
lv_obj_t * ui_weathermax5 = NULL;
lv_obj_t * ui_Panel24 = NULL;
lv_obj_t * ui_shijian6 = NULL;
lv_obj_t * ui_weathertype18 = NULL;
lv_obj_t * ui_weathermax6 = NULL;
lv_obj_t * ui_Panel25 = NULL;
lv_obj_t * ui_shijian7 = NULL;
lv_obj_t * ui_weathertype19 = NULL;
lv_obj_t * ui_weathermax7 = NULL;
lv_obj_t * ui_city2 = NULL;
lv_obj_t * ui_week2 = NULL;
lv_obj_t * ui_year2 = NULL;
// event funtions
void ui_event_weather2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_FADE_ON, 100, 0, &ui_Screen1_screen_init);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_BOTTOM) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_weather, LV_SCR_LOAD_ANIM_MOVE_BOTTOM, 100, 0, &ui_weather_screen_init);
    }
}

// build funtions

void ui_weather2_screen_init(void)
{
    ui_weather2 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_weather2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_weather2, lv_color_hex(0x000400), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_weather2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel4 = lv_obj_create(ui_weather2);
    lv_obj_set_width(ui_Panel4, 470);
    lv_obj_set_height(ui_Panel4, 164);
    lv_obj_set_x(ui_Panel4, -6);
    lv_obj_set_y(ui_Panel4, -42);
    lv_obj_set_align(ui_Panel4, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Panel4, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Panel4, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_set_scrollbar_mode(ui_Panel4, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_scroll_dir(ui_Panel4, LV_DIR_HOR);
    lv_obj_set_style_bg_color(ui_Panel4, lv_color_hex(0x000400), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel6 = lv_obj_create(ui_Panel4);
    lv_obj_set_width(ui_Panel6, 79);
    lv_obj_set_height(ui_Panel6, 161);
    lv_obj_set_x(ui_Panel6, -156);
    lv_obj_set_y(ui_Panel6, 9);
    lv_obj_set_align(ui_Panel6, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel6, lv_color_hex(0x000400), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel6, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_weathertime1 = lv_label_create(ui_Panel6);
    lv_obj_set_width(ui_weathertime1, 65);
    lv_obj_set_height(ui_weathertime1, 27);
    lv_obj_set_x(ui_weathertime1, 0);
    lv_obj_set_y(ui_weathertime1, -45);
    lv_obj_set_align(ui_weathertime1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_weathertime1, "11:00");
    lv_obj_set_style_text_color(ui_weathertime1, lv_color_hex(0xFF0500), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_weathertime1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_weathertime1, &ui_font_chinese, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_weathertype1 = lv_img_create(ui_Panel6);
    lv_img_set_src(ui_weathertype1, &ui_img_weather_sun_cloud_png);
    lv_obj_set_width(ui_weathertype1, 37);
    lv_obj_set_height(ui_weathertype1, 31);
    lv_obj_set_align(ui_weathertype1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_weathertype1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_weathertype1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_weather_temp1 = lv_label_create(ui_Panel6);
    lv_obj_set_width(ui_weather_temp1, 69);
    lv_obj_set_height(ui_weather_temp1, 39);
    lv_obj_set_x(ui_weather_temp1, 0);
    lv_obj_set_y(ui_weather_temp1, 45);
    lv_obj_set_align(ui_weather_temp1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_weather_temp1, "00°");
    lv_obj_set_style_text_color(ui_weather_temp1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_weather_temp1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_weather_temp1, &lv_font_montserrat_38, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel8 = lv_obj_create(ui_Panel4);
    lv_obj_set_width(ui_Panel8, 79);
    lv_obj_set_height(ui_Panel8, 161);
    lv_obj_set_x(ui_Panel8, -156);
    lv_obj_set_y(ui_Panel8, 9);
    lv_obj_set_align(ui_Panel8, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel8, lv_color_hex(0x000400), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel8, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_weathertime2 = lv_label_create(ui_Panel8);
    lv_obj_set_width(ui_weathertime2, 65);
    lv_obj_set_height(ui_weathertime2, 27);
    lv_obj_set_x(ui_weathertime2, 0);
    lv_obj_set_y(ui_weathertime2, -45);
    lv_obj_set_align(ui_weathertime2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_weathertime2, "11:00");
    lv_obj_set_style_text_color(ui_weathertime2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_weathertime2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_weathertime2, &ui_font_chinese, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_weathertype2 = lv_img_create(ui_Panel8);
    lv_img_set_src(ui_weathertype2, &ui_img_weather_sun_png);
    lv_obj_set_width(ui_weathertype2, 37);
    lv_obj_set_height(ui_weathertype2, 31);
    lv_obj_set_align(ui_weathertype2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_weathertype2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_weathertype2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_weather_temp2 = lv_label_create(ui_Panel8);
    lv_obj_set_width(ui_weather_temp2, 69);
    lv_obj_set_height(ui_weather_temp2, 39);
    lv_obj_set_x(ui_weather_temp2, 0);
    lv_obj_set_y(ui_weather_temp2, 45);
    lv_obj_set_align(ui_weather_temp2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_weather_temp2, "00°");
    lv_obj_set_style_text_color(ui_weather_temp2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_weather_temp2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_weather_temp2, &lv_font_montserrat_38, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel9 = lv_obj_create(ui_Panel4);
    lv_obj_set_width(ui_Panel9, 79);
    lv_obj_set_height(ui_Panel9, 161);
    lv_obj_set_x(ui_Panel9, -156);
    lv_obj_set_y(ui_Panel9, 9);
    lv_obj_set_align(ui_Panel9, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel9, lv_color_hex(0x000400), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel9, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_weathertime3 = lv_label_create(ui_Panel9);
    lv_obj_set_width(ui_weathertime3, 65);
    lv_obj_set_height(ui_weathertime3, 27);
    lv_obj_set_x(ui_weathertime3, 0);
    lv_obj_set_y(ui_weathertime3, -45);
    lv_obj_set_align(ui_weathertime3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_weathertime3, "11:00");
    lv_obj_set_style_text_color(ui_weathertime3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_weathertime3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_weathertime3, &ui_font_chinese, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_weathertype3 = lv_img_create(ui_Panel9);
    lv_img_set_src(ui_weathertype3, &ui_img_weather_cloud_fog_png);
    lv_obj_set_width(ui_weathertype3, 37);
    lv_obj_set_height(ui_weathertype3, 31);
    lv_obj_set_align(ui_weathertype3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_weathertype3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_weathertype3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_weather_temp3 = lv_label_create(ui_Panel9);
    lv_obj_set_width(ui_weather_temp3, 69);
    lv_obj_set_height(ui_weather_temp3, 39);
    lv_obj_set_x(ui_weather_temp3, 0);
    lv_obj_set_y(ui_weather_temp3, 45);
    lv_obj_set_align(ui_weather_temp3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_weather_temp3, "00°");
    lv_obj_set_style_text_color(ui_weather_temp3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_weather_temp3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_weather_temp3, &lv_font_montserrat_38, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel10 = lv_obj_create(ui_Panel4);
    lv_obj_set_width(ui_Panel10, 79);
    lv_obj_set_height(ui_Panel10, 161);
    lv_obj_set_x(ui_Panel10, -156);
    lv_obj_set_y(ui_Panel10, 9);
    lv_obj_set_align(ui_Panel10, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel10, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel10, lv_color_hex(0x000400), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel10, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_weathertime4 = lv_label_create(ui_Panel10);
    lv_obj_set_width(ui_weathertime4, 65);
    lv_obj_set_height(ui_weathertime4, 27);
    lv_obj_set_x(ui_weathertime4, 0);
    lv_obj_set_y(ui_weathertime4, -45);
    lv_obj_set_align(ui_weathertime4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_weathertime4, "11:00");
    lv_obj_set_style_text_color(ui_weathertime4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_weathertime4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_weathertime4, &ui_font_chinese, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_weathertype4 = lv_img_create(ui_Panel10);
    lv_img_set_src(ui_weathertype4, &ui_img_weather_cloud_png);
    lv_obj_set_width(ui_weathertype4, 37);
    lv_obj_set_height(ui_weathertype4, 31);
    lv_obj_set_align(ui_weathertype4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_weathertype4, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_weathertype4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_weather_temp4 = lv_label_create(ui_Panel10);
    lv_obj_set_width(ui_weather_temp4, 69);
    lv_obj_set_height(ui_weather_temp4, 39);
    lv_obj_set_x(ui_weather_temp4, 0);
    lv_obj_set_y(ui_weather_temp4, 45);
    lv_obj_set_align(ui_weather_temp4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_weather_temp4, "00°");
    lv_obj_set_style_text_color(ui_weather_temp4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_weather_temp4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_weather_temp4, &lv_font_montserrat_38, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel11 = lv_obj_create(ui_Panel4);
    lv_obj_set_width(ui_Panel11, 79);
    lv_obj_set_height(ui_Panel11, 161);
    lv_obj_set_x(ui_Panel11, -156);
    lv_obj_set_y(ui_Panel11, 9);
    lv_obj_set_align(ui_Panel11, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel11, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel11, lv_color_hex(0x000400), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel11, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel11, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel11, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_weathertime5 = lv_label_create(ui_Panel11);
    lv_obj_set_width(ui_weathertime5, 65);
    lv_obj_set_height(ui_weathertime5, 27);
    lv_obj_set_x(ui_weathertime5, 0);
    lv_obj_set_y(ui_weathertime5, -45);
    lv_obj_set_align(ui_weathertime5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_weathertime5, "11:00");
    lv_obj_set_style_text_color(ui_weathertime5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_weathertime5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_weathertime5, &ui_font_chinese, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_weathertype5 = lv_img_create(ui_Panel11);
    lv_img_set_src(ui_weathertype5, &ui_img_weather_sun_cloud_png);
    lv_obj_set_width(ui_weathertype5, 37);
    lv_obj_set_height(ui_weathertype5, 31);
    lv_obj_set_align(ui_weathertype5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_weathertype5, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_weathertype5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_weather_temp5 = lv_label_create(ui_Panel11);
    lv_obj_set_width(ui_weather_temp5, 69);
    lv_obj_set_height(ui_weather_temp5, 39);
    lv_obj_set_x(ui_weather_temp5, 0);
    lv_obj_set_y(ui_weather_temp5, 45);
    lv_obj_set_align(ui_weather_temp5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_weather_temp5, "00°");
    lv_obj_set_style_text_color(ui_weather_temp5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_weather_temp5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_weather_temp5, &lv_font_montserrat_38, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel12 = lv_obj_create(ui_Panel4);
    lv_obj_set_width(ui_Panel12, 79);
    lv_obj_set_height(ui_Panel12, 161);
    lv_obj_set_x(ui_Panel12, -156);
    lv_obj_set_y(ui_Panel12, 9);
    lv_obj_set_align(ui_Panel12, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel12, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel12, lv_color_hex(0x000400), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel12, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel12, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel12, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_weathertime6 = lv_label_create(ui_Panel12);
    lv_obj_set_width(ui_weathertime6, 65);
    lv_obj_set_height(ui_weathertime6, 27);
    lv_obj_set_x(ui_weathertime6, 0);
    lv_obj_set_y(ui_weathertime6, -45);
    lv_obj_set_align(ui_weathertime6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_weathertime6, "11:00");
    lv_obj_set_style_text_color(ui_weathertime6, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_weathertime6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_weathertime6, &ui_font_chinese, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_weathertype6 = lv_img_create(ui_Panel12);
    lv_img_set_src(ui_weathertype6, &ui_img_weather_sun_cloud_png);
    lv_obj_set_width(ui_weathertype6, 37);
    lv_obj_set_height(ui_weathertype6, 31);
    lv_obj_set_align(ui_weathertype6, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_weathertype6, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_weathertype6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_weather_temp6 = lv_label_create(ui_Panel12);
    lv_obj_set_width(ui_weather_temp6, 69);
    lv_obj_set_height(ui_weather_temp6, 39);
    lv_obj_set_x(ui_weather_temp6, 0);
    lv_obj_set_y(ui_weather_temp6, 45);
    lv_obj_set_align(ui_weather_temp6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_weather_temp6, "00°");
    lv_obj_set_style_text_color(ui_weather_temp6, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_weather_temp6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_weather_temp6, &lv_font_montserrat_38, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel13 = lv_obj_create(ui_Panel4);
    lv_obj_set_width(ui_Panel13, 79);
    lv_obj_set_height(ui_Panel13, 161);
    lv_obj_set_x(ui_Panel13, -156);
    lv_obj_set_y(ui_Panel13, 9);
    lv_obj_set_align(ui_Panel13, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel13, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel13, lv_color_hex(0x000400), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel13, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel13, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel13, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_weathertime7 = lv_label_create(ui_Panel13);
    lv_obj_set_width(ui_weathertime7, 65);
    lv_obj_set_height(ui_weathertime7, 27);
    lv_obj_set_x(ui_weathertime7, 0);
    lv_obj_set_y(ui_weathertime7, -45);
    lv_obj_set_align(ui_weathertime7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_weathertime7, "11:00");
    lv_obj_set_style_text_color(ui_weathertime7, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_weathertime7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_weathertime7, &ui_font_chinese, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_weathertype7 = lv_img_create(ui_Panel13);
    lv_img_set_src(ui_weathertype7, &ui_img_weather_sun_cloud_png);
    lv_obj_set_width(ui_weathertype7, 37);
    lv_obj_set_height(ui_weathertype7, 31);
    lv_obj_set_align(ui_weathertype7, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_weathertype7, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_weathertype7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_weather_temp7 = lv_label_create(ui_Panel13);
    lv_obj_set_width(ui_weather_temp7, 69);
    lv_obj_set_height(ui_weather_temp7, 39);
    lv_obj_set_x(ui_weather_temp7, 0);
    lv_obj_set_y(ui_weather_temp7, 45);
    lv_obj_set_align(ui_weather_temp7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_weather_temp7, "00°");
    lv_obj_set_style_text_color(ui_weather_temp7, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_weather_temp7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_weather_temp7, &lv_font_montserrat_38, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel14 = lv_obj_create(ui_Panel4);
    lv_obj_set_width(ui_Panel14, 79);
    lv_obj_set_height(ui_Panel14, 161);
    lv_obj_set_x(ui_Panel14, -156);
    lv_obj_set_y(ui_Panel14, 9);
    lv_obj_set_align(ui_Panel14, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel14, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel14, lv_color_hex(0x000400), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel14, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel14, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel14, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_weathertime8 = lv_label_create(ui_Panel14);
    lv_obj_set_width(ui_weathertime8, 65);
    lv_obj_set_height(ui_weathertime8, 27);
    lv_obj_set_x(ui_weathertime8, 0);
    lv_obj_set_y(ui_weathertime8, -45);
    lv_obj_set_align(ui_weathertime8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_weathertime8, "11:00");
    lv_obj_set_style_text_color(ui_weathertime8, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_weathertime8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_weathertime8, &ui_font_chinese, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_weathertype8 = lv_img_create(ui_Panel14);
    lv_img_set_src(ui_weathertype8, &ui_img_weather_sun_cloud_png);
    lv_obj_set_width(ui_weathertype8, 37);
    lv_obj_set_height(ui_weathertype8, 31);
    lv_obj_set_align(ui_weathertype8, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_weathertype8, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_weathertype8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_weather_temp8 = lv_label_create(ui_Panel14);
    lv_obj_set_width(ui_weather_temp8, 69);
    lv_obj_set_height(ui_weather_temp8, 39);
    lv_obj_set_x(ui_weather_temp8, 0);
    lv_obj_set_y(ui_weather_temp8, 45);
    lv_obj_set_align(ui_weather_temp8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_weather_temp8, "00°");
    lv_obj_set_style_text_color(ui_weather_temp8, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_weather_temp8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_weather_temp8, &lv_font_montserrat_38, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel15 = lv_obj_create(ui_Panel4);
    lv_obj_set_width(ui_Panel15, 79);
    lv_obj_set_height(ui_Panel15, 161);
    lv_obj_set_x(ui_Panel15, -156);
    lv_obj_set_y(ui_Panel15, 9);
    lv_obj_set_align(ui_Panel15, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel15, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel15, lv_color_hex(0x000400), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel15, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel15, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel15, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_weathertime9 = lv_label_create(ui_Panel15);
    lv_obj_set_width(ui_weathertime9, 65);
    lv_obj_set_height(ui_weathertime9, 27);
    lv_obj_set_x(ui_weathertime9, 0);
    lv_obj_set_y(ui_weathertime9, -45);
    lv_obj_set_align(ui_weathertime9, LV_ALIGN_CENTER);
    lv_label_set_text(ui_weathertime9, "11:00");
    lv_obj_set_style_text_color(ui_weathertime9, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_weathertime9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_weathertime9, &ui_font_chinese, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_weathertype9 = lv_img_create(ui_Panel15);
    lv_img_set_src(ui_weathertype9, &ui_img_weather_sun_cloud_png);
    lv_obj_set_width(ui_weathertype9, 37);
    lv_obj_set_height(ui_weathertype9, 31);
    lv_obj_set_align(ui_weathertype9, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_weathertype9, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_weathertype9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_weather_temp9 = lv_label_create(ui_Panel15);
    lv_obj_set_width(ui_weather_temp9, 69);
    lv_obj_set_height(ui_weather_temp9, 39);
    lv_obj_set_x(ui_weather_temp9, 0);
    lv_obj_set_y(ui_weather_temp9, 45);
    lv_obj_set_align(ui_weather_temp9, LV_ALIGN_CENTER);
    lv_label_set_text(ui_weather_temp9, "00°");
    lv_obj_set_style_text_color(ui_weather_temp9, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_weather_temp9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_weather_temp9, &lv_font_montserrat_38, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel16 = lv_obj_create(ui_Panel4);
    lv_obj_set_width(ui_Panel16, 79);
    lv_obj_set_height(ui_Panel16, 161);
    lv_obj_set_x(ui_Panel16, -156);
    lv_obj_set_y(ui_Panel16, 9);
    lv_obj_set_align(ui_Panel16, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel16, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel16, lv_color_hex(0x000400), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel16, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel16, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel16, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_weathertime10 = lv_label_create(ui_Panel16);
    lv_obj_set_width(ui_weathertime10, 65);
    lv_obj_set_height(ui_weathertime10, 27);
    lv_obj_set_x(ui_weathertime10, 0);
    lv_obj_set_y(ui_weathertime10, -45);
    lv_obj_set_align(ui_weathertime10, LV_ALIGN_CENTER);
    lv_label_set_text(ui_weathertime10, "11:00");
    lv_obj_set_style_text_color(ui_weathertime10, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_weathertime10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_weathertime10, &ui_font_chinese, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_weathertype10 = lv_img_create(ui_Panel16);
    lv_img_set_src(ui_weathertype10, &ui_img_weather_sun_cloud_png);
    lv_obj_set_width(ui_weathertype10, 37);
    lv_obj_set_height(ui_weathertype10, 31);
    lv_obj_set_align(ui_weathertype10, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_weathertype10, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_weathertype10, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_weather_temp10 = lv_label_create(ui_Panel16);
    lv_obj_set_width(ui_weather_temp10, 69);
    lv_obj_set_height(ui_weather_temp10, 39);
    lv_obj_set_x(ui_weather_temp10, 0);
    lv_obj_set_y(ui_weather_temp10, 45);
    lv_obj_set_align(ui_weather_temp10, LV_ALIGN_CENTER);
    lv_label_set_text(ui_weather_temp10, "00°");
    lv_obj_set_style_text_color(ui_weather_temp10, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_weather_temp10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_weather_temp10, &lv_font_montserrat_38, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel17 = lv_obj_create(ui_Panel4);
    lv_obj_set_width(ui_Panel17, 79);
    lv_obj_set_height(ui_Panel17, 161);
    lv_obj_set_x(ui_Panel17, -156);
    lv_obj_set_y(ui_Panel17, 9);
    lv_obj_set_align(ui_Panel17, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel17, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel17, lv_color_hex(0x000400), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel17, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel17, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel17, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_weathertime11 = lv_label_create(ui_Panel17);
    lv_obj_set_width(ui_weathertime11, 65);
    lv_obj_set_height(ui_weathertime11, 27);
    lv_obj_set_x(ui_weathertime11, 0);
    lv_obj_set_y(ui_weathertime11, -45);
    lv_obj_set_align(ui_weathertime11, LV_ALIGN_CENTER);
    lv_label_set_text(ui_weathertime11, "11:00");
    lv_obj_set_style_text_color(ui_weathertime11, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_weathertime11, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_weathertime11, &ui_font_chinese, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_weathertype11 = lv_img_create(ui_Panel17);
    lv_img_set_src(ui_weathertype11, &ui_img_weather_sun_cloud_png);
    lv_obj_set_width(ui_weathertype11, 37);
    lv_obj_set_height(ui_weathertype11, 31);
    lv_obj_set_align(ui_weathertype11, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_weathertype11, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_weathertype11, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_weather_temp11 = lv_label_create(ui_Panel17);
    lv_obj_set_width(ui_weather_temp11, 69);
    lv_obj_set_height(ui_weather_temp11, 39);
    lv_obj_set_x(ui_weather_temp11, 0);
    lv_obj_set_y(ui_weather_temp11, 45);
    lv_obj_set_align(ui_weather_temp11, LV_ALIGN_CENTER);
    lv_label_set_text(ui_weather_temp11, "00°");
    lv_obj_set_style_text_color(ui_weather_temp11, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_weather_temp11, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_weather_temp11, &lv_font_montserrat_38, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel18 = lv_obj_create(ui_Panel4);
    lv_obj_set_width(ui_Panel18, 79);
    lv_obj_set_height(ui_Panel18, 161);
    lv_obj_set_x(ui_Panel18, -156);
    lv_obj_set_y(ui_Panel18, 9);
    lv_obj_set_align(ui_Panel18, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel18, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel18, lv_color_hex(0x000400), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel18, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel18, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel18, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_weathertime12 = lv_label_create(ui_Panel18);
    lv_obj_set_width(ui_weathertime12, 65);
    lv_obj_set_height(ui_weathertime12, 27);
    lv_obj_set_x(ui_weathertime12, 0);
    lv_obj_set_y(ui_weathertime12, -45);
    lv_obj_set_align(ui_weathertime12, LV_ALIGN_CENTER);
    lv_label_set_text(ui_weathertime12, "11:00");
    lv_obj_set_style_text_color(ui_weathertime12, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_weathertime12, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_weathertime12, &ui_font_chinese, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_weathertype12 = lv_img_create(ui_Panel18);
    lv_img_set_src(ui_weathertype12, &ui_img_weather_sun_cloud_png);
    lv_obj_set_width(ui_weathertype12, 37);
    lv_obj_set_height(ui_weathertype12, 31);
    lv_obj_set_align(ui_weathertype12, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_weathertype12, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_weathertype12, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_weather_temp12 = lv_label_create(ui_Panel18);
    lv_obj_set_width(ui_weather_temp12, 69);
    lv_obj_set_height(ui_weather_temp12, 39);
    lv_obj_set_x(ui_weather_temp12, 0);
    lv_obj_set_y(ui_weather_temp12, 45);
    lv_obj_set_align(ui_weather_temp12, LV_ALIGN_CENTER);
    lv_label_set_text(ui_weather_temp12, "00°");
    lv_obj_set_style_text_color(ui_weather_temp12, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_weather_temp12, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_weather_temp12, &lv_font_montserrat_38, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel7 = lv_obj_create(ui_weather2);
    lv_obj_set_width(ui_Panel7, 485);
    lv_obj_set_height(ui_Panel7, 116);
    lv_obj_set_x(ui_Panel7, 0);
    lv_obj_set_y(ui_Panel7, 126);
    lv_obj_set_align(ui_Panel7, LV_ALIGN_CENTER);
    lv_obj_set_scrollbar_mode(ui_Panel7, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_scroll_dir(ui_Panel7, LV_DIR_VER);
    lv_obj_set_style_bg_color(ui_Panel7, lv_color_hex(0x000400), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel7, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel19 = lv_obj_create(ui_Panel7);
    lv_obj_set_width(ui_Panel19, 647);
    lv_obj_set_height(ui_Panel19, 42);
    lv_obj_set_x(ui_Panel19, 0);
    lv_obj_set_y(ui_Panel19, -40);
    lv_obj_set_align(ui_Panel19, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel19, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel19, lv_color_hex(0x000400), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel19, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel19, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel19, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_shijian1 = lv_label_create(ui_Panel19);
    lv_obj_set_width(ui_shijian1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_shijian1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_shijian1, -130);
    lv_obj_set_y(ui_shijian1, -1);
    lv_obj_set_align(ui_shijian1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_shijian1, "今天");
    lv_obj_set_style_text_color(ui_shijian1, lv_color_hex(0xED1E1E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_shijian1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_shijian1, &ui_font_chinese, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_weathertype13 = lv_img_create(ui_Panel19);
    lv_img_set_src(ui_weathertype13, &ui_img_weather_sun_cloud_png);
    lv_obj_set_width(ui_weathertype13, LV_SIZE_CONTENT);   /// 37
    lv_obj_set_height(ui_weathertype13, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_x(ui_weathertype13, 135);
    lv_obj_set_y(ui_weathertype13, -1);
    lv_obj_set_align(ui_weathertype13, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_weathertype13, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_weathertype13, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_weathermax1 = lv_label_create(ui_Panel19);
    lv_obj_set_width(ui_weathermax1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_weathermax1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_weathermax1, 7);
    lv_obj_set_y(ui_weathermax1, -1);
    lv_obj_set_align(ui_weathermax1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_weathermax1, "50°/20°");
    lv_obj_set_style_text_color(ui_weathermax1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_weathermax1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_weathermax1, &lv_font_montserrat_38, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel20 = lv_obj_create(ui_Panel7);
    lv_obj_set_width(ui_Panel20, 647);
    lv_obj_set_height(ui_Panel20, 42);
    lv_obj_set_x(ui_Panel20, 0);
    lv_obj_set_y(ui_Panel20, 20);
    lv_obj_set_align(ui_Panel20, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel20, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel20, lv_color_hex(0x000400), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel20, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel20, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel20, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_shijian2 = lv_label_create(ui_Panel20);
    lv_obj_set_width(ui_shijian2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_shijian2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_shijian2, -130);
    lv_obj_set_y(ui_shijian2, -1);
    lv_obj_set_align(ui_shijian2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_shijian2, "今天");
    lv_obj_set_style_text_color(ui_shijian2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_shijian2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_shijian2, &ui_font_chinese, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_weathertype14 = lv_img_create(ui_Panel20);
    lv_img_set_src(ui_weathertype14, &ui_img_weather_sun_cloud_png);
    lv_obj_set_width(ui_weathertype14, LV_SIZE_CONTENT);   /// 37
    lv_obj_set_height(ui_weathertype14, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_x(ui_weathertype14, 135);
    lv_obj_set_y(ui_weathertype14, -1);
    lv_obj_set_align(ui_weathertype14, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_weathertype14, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_weathertype14, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_weathermax2 = lv_label_create(ui_Panel20);
    lv_obj_set_width(ui_weathermax2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_weathermax2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_weathermax2, 7);
    lv_obj_set_y(ui_weathermax2, -1);
    lv_obj_set_align(ui_weathermax2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_weathermax2, "50°/20°");
    lv_obj_set_style_text_color(ui_weathermax2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_weathermax2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_weathermax2, &lv_font_montserrat_38, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel21 = lv_obj_create(ui_Panel7);
    lv_obj_set_width(ui_Panel21, 647);
    lv_obj_set_height(ui_Panel21, 42);
    lv_obj_set_x(ui_Panel21, 0);
    lv_obj_set_y(ui_Panel21, 80);
    lv_obj_set_align(ui_Panel21, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel21, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel21, lv_color_hex(0x000400), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel21, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel21, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel21, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_shijian3 = lv_label_create(ui_Panel21);
    lv_obj_set_width(ui_shijian3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_shijian3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_shijian3, -130);
    lv_obj_set_y(ui_shijian3, -1);
    lv_obj_set_align(ui_shijian3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_shijian3, "今天");
    lv_obj_set_style_text_color(ui_shijian3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_shijian3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_shijian3, &ui_font_chinese, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_weathertype15 = lv_img_create(ui_Panel21);
    lv_img_set_src(ui_weathertype15, &ui_img_weather_sun_cloud_png);
    lv_obj_set_width(ui_weathertype15, LV_SIZE_CONTENT);   /// 37
    lv_obj_set_height(ui_weathertype15, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_x(ui_weathertype15, 135);
    lv_obj_set_y(ui_weathertype15, -1);
    lv_obj_set_align(ui_weathertype15, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_weathertype15, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_weathertype15, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_weathermax3 = lv_label_create(ui_Panel21);
    lv_obj_set_width(ui_weathermax3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_weathermax3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_weathermax3, 7);
    lv_obj_set_y(ui_weathermax3, -1);
    lv_obj_set_align(ui_weathermax3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_weathermax3, "50°/20°");
    lv_obj_set_style_text_color(ui_weathermax3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_weathermax3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_weathermax3, &lv_font_montserrat_38, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel22 = lv_obj_create(ui_Panel7);
    lv_obj_set_width(ui_Panel22, 647);
    lv_obj_set_height(ui_Panel22, 42);
    lv_obj_set_x(ui_Panel22, 0);
    lv_obj_set_y(ui_Panel22, 140);
    lv_obj_set_align(ui_Panel22, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel22, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel22, lv_color_hex(0x000400), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel22, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel22, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel22, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_shijian4 = lv_label_create(ui_Panel22);
    lv_obj_set_width(ui_shijian4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_shijian4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_shijian4, -130);
    lv_obj_set_y(ui_shijian4, -1);
    lv_obj_set_align(ui_shijian4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_shijian4, "今天");
    lv_obj_set_style_text_color(ui_shijian4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_shijian4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_shijian4, &ui_font_chinese, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_weathertype16 = lv_img_create(ui_Panel22);
    lv_img_set_src(ui_weathertype16, &ui_img_weather_sun_cloud_png);
    lv_obj_set_width(ui_weathertype16, LV_SIZE_CONTENT);   /// 37
    lv_obj_set_height(ui_weathertype16, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_x(ui_weathertype16, 135);
    lv_obj_set_y(ui_weathertype16, -1);
    lv_obj_set_align(ui_weathertype16, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_weathertype16, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_weathertype16, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_weathermax4 = lv_label_create(ui_Panel22);
    lv_obj_set_width(ui_weathermax4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_weathermax4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_weathermax4, 7);
    lv_obj_set_y(ui_weathermax4, -1);
    lv_obj_set_align(ui_weathermax4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_weathermax4, "50°/20°");
    lv_obj_set_style_text_color(ui_weathermax4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_weathermax4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_weathermax4, &lv_font_montserrat_38, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel23 = lv_obj_create(ui_Panel7);
    lv_obj_set_width(ui_Panel23, 647);
    lv_obj_set_height(ui_Panel23, 42);
    lv_obj_set_x(ui_Panel23, 0);
    lv_obj_set_y(ui_Panel23, 200);
    lv_obj_set_align(ui_Panel23, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel23, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel23, lv_color_hex(0x000400), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel23, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel23, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel23, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_shijian5 = lv_label_create(ui_Panel23);
    lv_obj_set_width(ui_shijian5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_shijian5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_shijian5, -130);
    lv_obj_set_y(ui_shijian5, -1);
    lv_obj_set_align(ui_shijian5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_shijian5, "今天");
    lv_obj_set_style_text_color(ui_shijian5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_shijian5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_shijian5, &ui_font_chinese, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_weathertype17 = lv_img_create(ui_Panel23);
    lv_img_set_src(ui_weathertype17, &ui_img_weather_sun_cloud_png);
    lv_obj_set_width(ui_weathertype17, LV_SIZE_CONTENT);   /// 37
    lv_obj_set_height(ui_weathertype17, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_x(ui_weathertype17, 135);
    lv_obj_set_y(ui_weathertype17, -1);
    lv_obj_set_align(ui_weathertype17, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_weathertype17, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_weathertype17, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_weathermax5 = lv_label_create(ui_Panel23);
    lv_obj_set_width(ui_weathermax5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_weathermax5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_weathermax5, 7);
    lv_obj_set_y(ui_weathermax5, -1);
    lv_obj_set_align(ui_weathermax5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_weathermax5, "50°/20°");
    lv_obj_set_style_text_color(ui_weathermax5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_weathermax5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_weathermax5, &lv_font_montserrat_38, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel24 = lv_obj_create(ui_Panel7);
    lv_obj_set_width(ui_Panel24, 647);
    lv_obj_set_height(ui_Panel24, 42);
    lv_obj_set_x(ui_Panel24, 0);
    lv_obj_set_y(ui_Panel24, 260);
    lv_obj_set_align(ui_Panel24, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel24, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel24, lv_color_hex(0x000400), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel24, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel24, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel24, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_shijian6 = lv_label_create(ui_Panel24);
    lv_obj_set_width(ui_shijian6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_shijian6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_shijian6, -130);
    lv_obj_set_y(ui_shijian6, -1);
    lv_obj_set_align(ui_shijian6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_shijian6, "今天");
    lv_obj_set_style_text_color(ui_shijian6, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_shijian6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_shijian6, &ui_font_chinese, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_weathertype18 = lv_img_create(ui_Panel24);
    lv_img_set_src(ui_weathertype18, &ui_img_weather_sun_cloud_png);
    lv_obj_set_width(ui_weathertype18, LV_SIZE_CONTENT);   /// 37
    lv_obj_set_height(ui_weathertype18, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_x(ui_weathertype18, 135);
    lv_obj_set_y(ui_weathertype18, -1);
    lv_obj_set_align(ui_weathertype18, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_weathertype18, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_weathertype18, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_weathermax6 = lv_label_create(ui_Panel24);
    lv_obj_set_width(ui_weathermax6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_weathermax6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_weathermax6, 7);
    lv_obj_set_y(ui_weathermax6, -1);
    lv_obj_set_align(ui_weathermax6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_weathermax6, "50°/20°");
    lv_obj_set_style_text_color(ui_weathermax6, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_weathermax6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_weathermax6, &lv_font_montserrat_38, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel25 = lv_obj_create(ui_Panel7);
    lv_obj_set_width(ui_Panel25, 647);
    lv_obj_set_height(ui_Panel25, 42);
    lv_obj_set_x(ui_Panel25, 0);
    lv_obj_set_y(ui_Panel25, 320);
    lv_obj_set_align(ui_Panel25, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel25, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel25, lv_color_hex(0x000400), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel25, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel25, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel25, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_shijian7 = lv_label_create(ui_Panel25);
    lv_obj_set_width(ui_shijian7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_shijian7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_shijian7, -130);
    lv_obj_set_y(ui_shijian7, -1);
    lv_obj_set_align(ui_shijian7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_shijian7, "今天");
    lv_obj_set_style_text_color(ui_shijian7, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_shijian7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_shijian7, &ui_font_chinese, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_weathertype19 = lv_img_create(ui_Panel25);
    lv_img_set_src(ui_weathertype19, &ui_img_weather_sun_cloud_png);
    lv_obj_set_width(ui_weathertype19, LV_SIZE_CONTENT);   /// 37
    lv_obj_set_height(ui_weathertype19, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_x(ui_weathertype19, 135);
    lv_obj_set_y(ui_weathertype19, -1);
    lv_obj_set_align(ui_weathertype19, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_weathertype19, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_weathertype19, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_weathermax7 = lv_label_create(ui_Panel25);
    lv_obj_set_width(ui_weathermax7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_weathermax7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_weathermax7, 7);
    lv_obj_set_y(ui_weathermax7, -1);
    lv_obj_set_align(ui_weathermax7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_weathermax7, "50°/20°");
    lv_obj_set_style_text_color(ui_weathermax7, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_weathermax7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_weathermax7, &lv_font_montserrat_38, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_city2 = lv_label_create(ui_weather2);
    lv_obj_set_width(ui_city2, 98);
    lv_obj_set_height(ui_city2, 46);
    lv_obj_set_x(ui_city2, 0);
    lv_obj_set_y(ui_city2, -181);
    lv_obj_set_align(ui_city2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_city2, "南海");
    lv_obj_set_style_text_color(ui_city2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_city2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_city2, &ui_font_chinese2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_week2 = lv_label_create(ui_weather2);
    lv_obj_set_width(ui_week2, 48);
    lv_obj_set_height(ui_week2, 25);
    lv_obj_set_x(ui_week2, 73);
    lv_obj_set_y(ui_week2, -128);
    lv_obj_set_align(ui_week2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_week2, "周一");
    lv_obj_set_style_text_color(ui_week2, lv_color_hex(0x6D6D6D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_week2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_week2, &ui_font_chinese, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_year2 = lv_label_create(ui_weather2);
    lv_obj_set_width(ui_year2, 141);
    lv_obj_set_height(ui_year2, 27);
    lv_obj_set_x(ui_year2, -44);
    lv_obj_set_y(ui_year2, -128);
    lv_obj_set_align(ui_year2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_year2, "2026/12/12");
    lv_obj_set_style_text_color(ui_year2, lv_color_hex(0x6D6D6D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_year2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_year2, &ui_font_chinese, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_weather2, ui_event_weather2, LV_EVENT_ALL, NULL);

}

void ui_weather2_screen_destroy(void)
{
    if(ui_weather2) lv_obj_del(ui_weather2);

    // NULL screen variables
    ui_weather2 = NULL;
    ui_Panel4 = NULL;
    ui_Panel6 = NULL;
    ui_weathertime1 = NULL;
    ui_weathertype1 = NULL;
    ui_weather_temp1 = NULL;
    ui_Panel8 = NULL;
    ui_weathertime2 = NULL;
    ui_weathertype2 = NULL;
    ui_weather_temp2 = NULL;
    ui_Panel9 = NULL;
    ui_weathertime3 = NULL;
    ui_weathertype3 = NULL;
    ui_weather_temp3 = NULL;
    ui_Panel10 = NULL;
    ui_weathertime4 = NULL;
    ui_weathertype4 = NULL;
    ui_weather_temp4 = NULL;
    ui_Panel11 = NULL;
    ui_weathertime5 = NULL;
    ui_weathertype5 = NULL;
    ui_weather_temp5 = NULL;
    ui_Panel12 = NULL;
    ui_weathertime6 = NULL;
    ui_weathertype6 = NULL;
    ui_weather_temp6 = NULL;
    ui_Panel13 = NULL;
    ui_weathertime7 = NULL;
    ui_weathertype7 = NULL;
    ui_weather_temp7 = NULL;
    ui_Panel14 = NULL;
    ui_weathertime8 = NULL;
    ui_weathertype8 = NULL;
    ui_weather_temp8 = NULL;
    ui_Panel15 = NULL;
    ui_weathertime9 = NULL;
    ui_weathertype9 = NULL;
    ui_weather_temp9 = NULL;
    ui_Panel16 = NULL;
    ui_weathertime10 = NULL;
    ui_weathertype10 = NULL;
    ui_weather_temp10 = NULL;
    ui_Panel17 = NULL;
    ui_weathertime11 = NULL;
    ui_weathertype11 = NULL;
    ui_weather_temp11 = NULL;
    ui_Panel18 = NULL;
    ui_weathertime12 = NULL;
    ui_weathertype12 = NULL;
    ui_weather_temp12 = NULL;
    ui_Panel7 = NULL;
    ui_Panel19 = NULL;
    ui_shijian1 = NULL;
    ui_weathertype13 = NULL;
    ui_weathermax1 = NULL;
    ui_Panel20 = NULL;
    ui_shijian2 = NULL;
    ui_weathertype14 = NULL;
    ui_weathermax2 = NULL;
    ui_Panel21 = NULL;
    ui_shijian3 = NULL;
    ui_weathertype15 = NULL;
    ui_weathermax3 = NULL;
    ui_Panel22 = NULL;
    ui_shijian4 = NULL;
    ui_weathertype16 = NULL;
    ui_weathermax4 = NULL;
    ui_Panel23 = NULL;
    ui_shijian5 = NULL;
    ui_weathertype17 = NULL;
    ui_weathermax5 = NULL;
    ui_Panel24 = NULL;
    ui_shijian6 = NULL;
    ui_weathertype18 = NULL;
    ui_weathermax6 = NULL;
    ui_Panel25 = NULL;
    ui_shijian7 = NULL;
    ui_weathertype19 = NULL;
    ui_weathermax7 = NULL;
    ui_city2 = NULL;
    ui_week2 = NULL;
    ui_year2 = NULL;

}
